import { NextResponse } from "next/server";
import { isAdminAuthenticated } from "@/lib/adminAuth";
import { lmsApiError, readJsonObject } from "@/lib/lms/apiResponse";
import { requireLmsAdminClient } from "@/lib/lms/adminData";
import { initializeRecordedLearningForSession, saveSessionRecordingRequirements } from "@/lib/lms/recordingService";

async function admin() { return isAdminAuthenticated(); }
export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) { if (!(await admin())) return NextResponse.json({ message: "Unauthorized." }, { status: 401 }); const { id } = await params; const supabase = requireLmsAdminClient(); try { const [requirements, assignments] = await Promise.all([supabase.from("session_recording_requirements").select("*").eq("class_session_id", id).maybeSingle(), supabase.from("recording_learning_assignments").select("*, recording_progress(*), recording_requirement_statuses(*)").eq("class_session_id", id)]); if (requirements.error || assignments.error) throw new Error("query"); return NextResponse.json({ requirements: requirements.data, assignments: assignments.data ?? [] }); } catch (error) { return lmsApiError(error, "Recorded-learning configuration could not be loaded."); } }
export async function POST(_request: Request, { params }: { params: Promise<{ id: string }> }) { if (!(await admin())) return NextResponse.json({ message: "Unauthorized." }, { status: 401 }); const { id } = await params; try { return NextResponse.json(await initializeRecordedLearningForSession(requireLmsAdminClient(), id, { actorLabel: "REALMS Admin" }), { status: 201 }); } catch (error) { return lmsApiError(error, "Recorded learning could not be initialized."); } }
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { if (!(await admin())) return NextResponse.json({ message: "Unauthorized." }, { status: 401 }); const body = await readJsonObject(request); if (!body) return NextResponse.json({ message: "Valid requirements are required." }, { status: 400 }); const { id } = await params; try { return NextResponse.json({ requirements: await saveSessionRecordingRequirements(requireLmsAdminClient(), id, body, { actorLabel: "REALMS Admin" }) }); } catch (error) { return lmsApiError(error, "Recorded-learning requirements could not be saved."); } }
