import { NextResponse } from "next/server";
import { revalidatePath } from "next/cache";
import { isAdminAuthenticated } from "@/lib/adminAuth";
import { lmsApiError, readJsonObject } from "@/lib/lms/apiResponse";
import { requireLmsAdminClient } from "@/lib/lms/adminData";
import { createRecordingCheckpoint, removeRecordingCheckpoint, updateRecordingCheckpoint } from "@/lib/lms/recordingService";

export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) { if (!(await isAdminAuthenticated())) return NextResponse.json({ message: "Unauthorized." }, { status: 401 }); const body = await readJsonObject(request); if (!body) return NextResponse.json({ message: "Valid checkpoint details are required." }, { status: 400 }); const { id } = await params; try { return NextResponse.json({ checkpoint: await createRecordingCheckpoint(requireLmsAdminClient(), id, body, { actorLabel: "REALMS Admin" }) }, { status: 201 }); } catch (error) { return lmsApiError(error, "Recording checkpoint could not be created."); } }
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { if (!(await isAdminAuthenticated())) return NextResponse.json({ message: "Unauthorized." }, { status: 401 }); const body = await readJsonObject(request); if (!body) return NextResponse.json({ message: "Valid checkpoint details are required." }, { status: 400 }); const { id } = await params; try { const result = await updateRecordingCheckpoint(requireLmsAdminClient(), id, body, { actorLabel: "REALMS Admin" }); revalidatePath(`/admin/sessions/${result.sessionId}`); return NextResponse.json({ checkpointId: result.checkpointId }); } catch (error) { return lmsApiError(error, "Recording checkpoint could not be updated."); } }
export async function DELETE(_request: Request, { params }: { params: Promise<{ id: string }> }) { if (!(await isAdminAuthenticated())) return NextResponse.json({ message: "Unauthorized." }, { status: 401 }); const { id } = await params; try { const result = await removeRecordingCheckpoint(requireLmsAdminClient(), id, { actorLabel: "REALMS Admin" }); revalidatePath(`/admin/sessions/${result.sessionId}`); return NextResponse.json({ checkpointId: result.checkpointId }); } catch (error) { return lmsApiError(error, "Recording checkpoint could not be removed."); } }
