"use client";

import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";

import { absenceReasonCategories, absenceReasonLabels } from "@/lib/lms/absence";

type SessionOption = { id: string; title: string; scheduledStartAt: string | null; courseCode: string; courseTitle: string };

async function jsonRequest(url: string, init: RequestInit = {}) {
  const response = await fetch(url, { ...init, headers: { "Content-Type": "application/json", ...(init.headers ?? {}) } }); const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(typeof data.message === "string" ? data.message : "The request could not be completed."); return data;
}

export function NewAbsenceRequestForm({ sessions }: { sessions: SessionOption[] }) {
  const router = useRouter(); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const form = new FormData(event.currentTarget);
    try { const created = await jsonRequest("/api/student/absences", { method: "POST", body: JSON.stringify({ class_session_id: form.get("class_session_id"), known_in_advance: form.get("known_in_advance") === "yes", reason_category: form.get("reason_category"), explanation: form.get("explanation"), student_requested_makeup: form.get("student_requested_makeup") === "on" }) }); const id = created.request.id; await jsonRequest(`/api/student/absences/${id}/submit`, { method: "POST" }); router.push(`/student/absences/${id}`); router.refresh(); }
    catch (error) { setMessage(error instanceof Error ? error.message : "The absence request could not be submitted."); setBusy(false); }
  }
  return <form onSubmit={submit} className="space-y-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><label className="block text-sm font-semibold text-[#071327]">Required class session<select name="class_session_id" required className="mt-2 min-h-12 w-full rounded-xl border border-slate-300 px-3"><option value="">Choose a session</option>{sessions.map((session) => <option key={session.id} value={session.id}>{session.courseCode} · {session.title} · {session.scheduledStartAt ? new Date(session.scheduledStartAt).toLocaleDateString("en-NG") : "Date pending"}</option>)}</select></label><fieldset><legend className="text-sm font-semibold text-[#071327]">Is this absence known in advance?</legend><div className="mt-2 flex gap-5"><label><input required type="radio" name="known_in_advance" value="yes" /> Yes</label><label><input required type="radio" name="known_in_advance" value="no" /> No</label></div></fieldset><label className="block text-sm font-semibold text-[#071327]">Reason category<select name="reason_category" required className="mt-2 min-h-12 w-full rounded-xl border border-slate-300 px-3"><option value="">Choose a category</option>{absenceReasonCategories.map((reason) => <option key={reason} value={reason}>{absenceReasonLabels[reason]}</option>)}</select></label><label className="block text-sm font-semibold text-[#071327]">Concise explanation<textarea name="explanation" required minLength={10} maxLength={4000} rows={6} className="mt-2 w-full rounded-xl border border-slate-300 p-3" placeholder="Share only the information REALMS needs to review this request. Detailed medical information is not required." /></label><label className="flex gap-3 text-sm text-slate-700"><input type="checkbox" name="student_requested_makeup" defaultChecked className="mt-1" />I am requesting the academic make-up needed to recover the missed learning.</label>{message ? <p role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-800">{message}</p> : null}<button disabled={busy || !sessions.length} className="min-h-12 rounded-xl bg-[#0b315c] px-6 font-semibold text-white disabled:opacity-50">{busy ? "Submitting…" : "Submit Absence Request"}</button></form>;
}

export function StudentAbsenceActions({ request }: { request: { id: string; status: string; knownInAdvance: boolean; reasonCategory: string; explanation: string; studentRequestedMakeup: boolean } }) {
  const router = useRouter(); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const editable = ["draft", "more_information_required"].includes(request.status); const withdrawable = ["draft", "submitted", "under_review", "more_information_required"].includes(request.status);
  async function update(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const form = new FormData(event.currentTarget); try { await jsonRequest(`/api/student/absences/${request.id}`, { method: "PATCH", body: JSON.stringify({ known_in_advance: form.get("known_in_advance") === "yes", reason_category: form.get("reason_category"), explanation: form.get("explanation"), student_requested_makeup: form.get("student_requested_makeup") === "on" }) }); await jsonRequest(`/api/student/absences/${request.id}/submit`, { method: "POST" }); setMessage("Your updated request has been resubmitted."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Update failed."); } finally { setBusy(false); } }
  async function withdraw() { if (!window.confirm("Withdraw this absence request?")) return; setBusy(true); try { await jsonRequest(`/api/student/absences/${request.id}/withdraw`, { method: "POST" }); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Withdrawal failed."); setBusy(false); } }
  async function evidence(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); try { await jsonRequest(`/api/student/absences/${request.id}/evidence`, { method: "POST", body: JSON.stringify({ title: form.get("title"), description: form.get("description"), external_url: form.get("external_url") }) }); setMessage("Supporting-evidence metadata was saved securely for authorised review."); event.currentTarget.reset(); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Evidence could not be saved."); } finally { setBusy(false); } }
  return <div className="space-y-5">{editable ? <form onSubmit={update} className="space-y-4 rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-semibold text-[#071327]">Update and resubmit</h2><div className="flex gap-5 text-sm"><label><input type="radio" name="known_in_advance" value="yes" defaultChecked={request.knownInAdvance} /> Known in advance</label><label><input type="radio" name="known_in_advance" value="no" defaultChecked={!request.knownInAdvance} /> Not known in advance</label></div><select name="reason_category" defaultValue={request.reasonCategory} className="min-h-11 w-full rounded-xl border border-slate-300 px-3">{absenceReasonCategories.map((reason) => <option key={reason} value={reason}>{absenceReasonLabels[reason]}</option>)}</select><textarea name="explanation" defaultValue={request.explanation} required rows={5} className="w-full rounded-xl border border-slate-300 p-3" /><label className="flex gap-3 text-sm"><input type="checkbox" name="student_requested_makeup" defaultChecked={request.studentRequestedMakeup} />Request academic make-up</label><button disabled={busy} className="rounded-xl bg-[#0b315c] px-5 py-3 font-semibold text-white">Update and Resubmit</button></form> : null}{withdrawable ? <button type="button" onClick={withdraw} disabled={busy} className="rounded-xl border border-slate-300 bg-white px-5 py-3 text-sm font-semibold">Withdraw Request</button> : null}{["draft", "submitted", "under_review", "more_information_required"].includes(request.status) ? <form onSubmit={evidence} className="space-y-3 rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-[#071327]">Add supporting evidence</h2><p className="text-sm text-slate-600">Evidence is optional unless REALMS requests it. Do not include unnecessary medical or personal details.</p><input name="title" required placeholder="Evidence title" className="min-h-11 w-full rounded-xl border border-slate-300 px-3" /><textarea name="description" required placeholder="Concise description" rows={3} className="w-full rounded-xl border border-slate-300 p-3" /><input name="external_url" type="url" placeholder="Secure HTTPS link (optional)" className="min-h-11 w-full rounded-xl border border-slate-300 px-3" /><button disabled={busy} className="rounded-xl bg-[#0b315c] px-5 py-3 font-semibold text-white">Add Evidence Metadata</button></form> : null}{message ? <p role="status" className="rounded-xl bg-slate-100 p-3 text-sm">{message}</p> : null}</div>;
}
