import { NextResponse } from "next/server";
import { isAdminAuthenticated } from "@/lib/adminAuth";
import { courseCategories, isOneOf, isUuid, readText } from "@/lib/lms/adminConstants";
import { recordLmsAudit } from "@/lib/lms/adminAudit";
import { fetchAdminCourse, requireLmsAdminClient } from "@/lib/lms/adminData";

function list(value: unknown) { return typeof value === "string" ? value.split(/\r?\n/).map((item) => item.trim()).filter(Boolean).slice(0, 100) : []; }
export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) { if (!(await isAdminAuthenticated())) return NextResponse.json({ message: "Unauthorized." }, { status: 401 }); const { id } = await params; if (!isUuid(id)) return NextResponse.json({ message: "Course not found." }, { status: 404 }); try { return NextResponse.json(await fetchAdminCourse(requireLmsAdminClient(), id)); } catch { return NextResponse.json({ message: "Course could not be loaded." }, { status: 500 }); } }
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {
  if (!(await isAdminAuthenticated())) return NextResponse.json({ message: "Unauthorized." }, { status: 401 }); const { id } = await params; if (!isUuid(id)) return NextResponse.json({ message: "Course not found." }, { status: 404 }); const body = await request.json().catch(() => null) as Record<string, unknown> | null;
  const code = readText(body?.code, 40); const title = readText(body?.title, 240); if (!body || !code || !title || !isOneOf(courseCategories, body.course_category) || typeof body.active !== "boolean") return NextResponse.json({ message: "Valid course details are required." }, { status: 400 });
  const route = body.discipleship_route === "" ? null : body.discipleship_route; const pathway = body.skill_pathway === "" ? null : body.skill_pathway; if (route !== null && route !== "foundational" && route !== "advanced") return NextResponse.json({ message: "Invalid discipleship route." }, { status: 400 }); if (pathway !== null && pathway !== "web_development" && pathway !== "cybersecurity_foundations") return NextResponse.json({ message: "Invalid skill pathway." }, { status: 400 });
  const sequence = body.sequence_number === "" || body.sequence_number == null ? null : Number(body.sequence_number); if (sequence !== null && (!Number.isInteger(sequence) || sequence < 1)) return NextResponse.json({ message: "Sequence must be a positive whole number." }, { status: 400 });
  const supabase = requireLmsAdminClient(); const record = await fetchAdminCourse(supabase, id); if (record.course.code !== code && record.enrollmentCount > 0) return NextResponse.json({ message: "Course code cannot be changed because student enrolments depend on it." }, { status: 409 });
  const updates = { code, title, course_category: body.course_category, discipleship_route: route, skill_pathway: pathway, sequence_number: sequence, description: readText(body.description), course_purpose: readText(body.course_purpose), delivery_week: readText(body.delivery_week, 120), default_schedule_text: readText(body.default_schedule_text, 500), learning_outcomes: list(body.learning_outcomes), assessed_evidence: list(body.assessed_evidence), internal_notes: readText(body.internal_notes), active: body.active, updated_at: new Date().toISOString() };
  const result = await supabase.from("courses").update(updates).eq("id", id).select("*").single(); if (result.error) return NextResponse.json({ message: result.error.code === "23505" ? "That course code is already in use." : "Course could not be updated." }, { status: result.error.code === "23505" ? 409 : 500 }); await recordLmsAudit(supabase, { action: "course_updated", entityType: "course", entityId: id, metadata: { previous: record.course, next: result.data } }); return NextResponse.json({ course: result.data });
}
