import Link from "next/link";
import { StudentPanel, formatStudentDate } from "@/components/student/StudentUi";
import { requireRole } from "@/lib/lms/auth";
import { courseLabel, fetchStudentQuizzes } from "@/lib/lms/assessmentData";
import { humanizeAssessment } from "@/lib/lms/assessment";
import { requireLmsAdminClient } from "@/lib/lms/adminData";
type Row = Record<string, unknown>;
function status(quiz: Row) { const latest = quiz.latest_attempt as Row | null; if (latest?.attempt_status === "awaiting_review") return "awaiting_review"; if (latest?.attempt_status === "graded") return "completed"; if (latest?.attempt_status === "in_progress") return "in_progress"; if (quiz.opens_at && Date.parse(String(quiz.opens_at)) > Date.now()) return "upcoming"; if (quiz.closes_at && Date.parse(String(quiz.closes_at)) <= Date.now()) return "closed"; return "available_now"; }
export default async function StudentQuizzesPage() { const { user } = await requireRole("student"); const quizzes = await fetchStudentQuizzes(requireLmsAdminClient(), user.id) as unknown as Row[]; const sections = [["Available Now", ["available_now", "in_progress"]], ["Upcoming", ["upcoming"]], ["Completed", ["completed"]], ["Awaiting Review", ["awaiting_review"]]] as const; return <div className="space-y-6"><header><p className="text-sm font-semibold uppercase tracking-wider text-amber-700">Assessment</p><h1 className="mt-2 text-3xl font-semibold text-[#071327]">Quizzes</h1><p className="mt-2 text-slate-600">Secure quizzes from your enrolled courses. Attempt timers are controlled by the server.</p></header>{sections.map(([title, states]) => { const items = quizzes.filter((quiz) => (states as readonly string[]).includes(status(quiz))); if (!items.length) return null; return <StudentPanel key={title} title={title}><div className="grid gap-3 lg:grid-cols-2">{items.map((quiz) => { const attempts = quiz.attempts as Row[]; const latest = quiz.latest_attempt as Row | null; return <Link key={String(quiz.id)} href={`/student/quizzes/${String(quiz.id)}`} className="rounded-xl border border-slate-200 p-4 hover:border-amber-300"><p className="text-xs font-semibold uppercase text-amber-700">{courseLabel(quiz)}</p><h2 className="mt-2 font-semibold">{String(quiz.title)}</h2><dl className="mt-3 grid grid-cols-2 gap-2 text-sm text-slate-600"><div><dt className="font-semibold text-slate-800">Window</dt><dd>{quiz.opens_at ? formatStudentDate(String(quiz.opens_at), true) : "Open"} – {quiz.closes_at ? formatStudentDate(String(quiz.closes_at), true) : "No close"}</dd></div><div><dt className="font-semibold text-slate-800">Duration</dt><dd>{quiz.duration_minutes ? `${String(quiz.duration_minutes)} minutes` : "Untimed"}</dd></div><div><dt className="font-semibold text-slate-800">Attempts remaining</dt><dd>{Math.max(0, Number(quiz.max_attempts) - attempts.length)}</dd></div><div><dt className="font-semibold text-slate-800">Status</dt><dd>{humanizeAssessment(status(quiz))}</dd></div>{quiz.show_score_after_submission && latest?.score_percentage != null ? <div><dt className="font-semibold text-slate-800">Latest score</dt><dd>{String(latest.score_percentage)}%</dd></div> : null}</dl></Link>; })}</div></StudentPanel>; })}{quizzes.length === 0 ? <StudentPanel title="No published quizzes"><p className="text-sm text-slate-600">There are no published quizzes for your enrolled courses.</p></StudentPanel> : null}</div>; }
