import Link from "next/link";
import { notFound } from "next/navigation";

import { LearningBreadcrumbs, LearningSessionList, formatDuration } from "@/components/student/StudentLearningUi";
import { DataCard, EmptyState, formatStudentDate, humanizeStudentValue, StudentPanel } from "@/components/student/StudentUi";
import { getStudentCourseDetail } from "@/lib/lms/studentLearning";
import { requireRole } from "@/lib/lms/auth";
import { fetchStudentAssignments, fetchStudentQuizzes } from "@/lib/lms/assessmentData";
import { humanizeAssessment } from "@/lib/lms/assessment";
import { requireLmsAdminClient } from "@/lib/lms/adminData";

export default async function StudentCourseDetailPage({ params }: { params: Promise<{ courseEnrollmentId: string }> }) {
  const { courseEnrollmentId } = await params;
  const { user } = await requireRole("student");
  const detail = await getStudentCourseDetail(courseEnrollmentId);
  if (!detail) notFound();
  const { course } = detail;
  const assessmentClient = requireLmsAdminClient();
  const [allAssignments, allQuizzes] = await Promise.all([fetchStudentAssignments(assessmentClient, user.id), fetchStudentQuizzes(assessmentClient, user.id)]);
  const assignments = allAssignments.filter((item) => item.cohort_course_id === course.offeringId);
  const quizzes = allQuizzes.filter((item) => item.cohort_course_id === course.offeringId);
  const hasSessions = detail.upcomingSessions.length > 0 || detail.pastSessions.length > 0;
  return <div className="space-y-6"><div><LearningBreadcrumbs items={[{ href: "/student/courses", label: "My Courses" }, { label: course.code }]} /><header className="rounded-3xl bg-[linear-gradient(135deg,#092648,#0e3a68)] p-6 text-white shadow-lg md:p-8"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[var(--realm-gold-soft)]">{course.code}</p><h1 className="mt-3 max-w-4xl text-3xl font-semibold tracking-tight md:text-4xl">{course.title}</h1>{course.description ? <p className="mt-4 max-w-3xl leading-7 text-white/75">{course.description}</p> : null}<dl className="mt-6 grid gap-4 border-t border-white/15 pt-5 sm:grid-cols-2 lg:grid-cols-4"><HeaderItem label="Programme Component" value={course.componentLabel} /><HeaderItem label="Cohort" value={course.cohortName} /><HeaderItem label="Delivery Mode" value={humanizeStudentValue(course.deliveryMode)} /><HeaderItem label="Schedule" value={course.schedule ?? "Not scheduled"} /></dl></header></div>

    <StudentPanel title="Course Overview"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><DataCard label="Category" value={course.categoryLabel} />{course.deliveryWeek ? <DataCard label="Delivery Week" value={course.deliveryWeek} /> : null}<DataCard label="Facilitator" value={course.facilitators.length ? course.facilitators.join(", ") : "To be announced"} /><DataCard label="Class Sessions" value={String(course.sessionCount)} detail={`${course.summaryCount} summaries · ${course.recordingCount} recordings`} /></div>{course.purpose ? <div className="mt-6 border-t border-slate-200 pt-5"><h3 className="font-semibold text-[#071327]">Course Purpose</h3><p className="mt-2 max-w-4xl leading-7 text-slate-700">{course.purpose}</p></div> : null}{course.isCapstone ? <p className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-900">Published capstone work appears in Assignments. A graded capstone does not by itself establish graduation eligibility.</p> : null}</StudentPanel>

    {course.learningOutcomes.length ? <StudentPanel title="What You Will Learn"><ul className="space-y-3 text-slate-700">{course.learningOutcomes.map((outcome, index) => <li key={index} className="flex gap-3 leading-7"><span aria-hidden="true" className="text-amber-700">•</span><span>{outcome}</span></li>)}</ul></StudentPanel> : null}

    <StudentPanel title="Class Sessions" description="Session status describes the teaching event, not individual learning completion.">{!hasSessions ? <EmptyState>No class sessions have been published for this course yet.</EmptyState> : <div className="space-y-7">{detail.upcomingSessions.length ? <section><h3 className="mb-3 font-semibold text-[#071327]">Upcoming</h3><LearningSessionList sessions={detail.upcomingSessions} empty="" /></section> : null}{detail.pastSessions.length ? <section><h3 className="mb-3 font-semibold text-[#071327]">Completed / Past</h3><LearningSessionList sessions={detail.pastSessions} empty="" /></section> : null}</div>}</StudentPanel>

    <div className="grid gap-6 xl:grid-cols-2"><StudentPanel title="Assignments">{assignments.length ? <ul className="space-y-3">{assignments.map((item) => <li key={item.id}><Link href={`/student/assignments/${item.id}`} className="block rounded-xl border border-slate-200 p-4"><strong>{item.title}</strong><p className="mt-1 text-sm text-slate-600">{humanizeAssessment(item.assignment_type)} · {item.due_at ? formatStudentDate(item.due_at, true) : "No fixed deadline"}</p></Link></li>)}</ul> : <EmptyState>No published assignments for this course.</EmptyState>}</StudentPanel><StudentPanel title="Quizzes">{quizzes.length ? <ul className="space-y-3">{quizzes.map((item) => <li key={item.id}><Link href={`/student/quizzes/${item.id}`} className="block rounded-xl border border-slate-200 p-4"><strong>{item.title}</strong><p className="mt-1 text-sm text-slate-600">{item.opens_at ? formatStudentDate(item.opens_at, true) : "Open"} · {item.duration_minutes ? `${item.duration_minutes} minutes` : "Untimed"}</p></Link></li>)}</ul> : <EmptyState>No published quizzes for this course.</EmptyState>}</StudentPanel></div>

    <StudentPanel title="Class Summary Archive" description="Current published summaries from this course.">{detail.summaryArchive.length ? <ul className="space-y-3">{detail.summaryArchive.map((summary) => <li key={summary.id} className="flex flex-col gap-4 rounded-xl border border-slate-200 bg-slate-50 p-4 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-amber-700">{summary.sessionTitle}</p><h3 className="mt-1 font-semibold text-[#071327]">{summary.title}</h3><p className="mt-1 text-sm text-slate-600">{formatStudentDate(summary.sessionDate)} · Version {summary.versionNumber} · Updated {formatStudentDate(summary.updatedAt, true)}</p></div><Link href={`/student/sessions/${summary.sessionId}#summary`} className="inline-flex min-h-11 shrink-0 items-center justify-center rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-[#0b315c] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-amber-700">Read Summary</Link></li>)}</ul> : <EmptyState>No class summaries are currently available.</EmptyState>}</StudentPanel>

    <div className="grid gap-6 xl:grid-cols-2"><StudentPanel title="Course Resources" description="Resources published for sessions in this course.">{detail.resources.length ? <ul className="space-y-3">{detail.resources.map((resource) => <li key={resource.id} className="rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-amber-700">{humanizeStudentValue(resource.resourceType)}</p><h3 className="mt-1 font-semibold text-[#071327]">{resource.title}</h3><p className="mt-1 text-sm text-slate-600">{resource.sessionTitle}</p><div className="mt-3 flex flex-wrap gap-4 text-sm">{resource.externalUrl ? <a href={resource.externalUrl} target="_blank" rel="noreferrer noopener" className="font-semibold text-amber-800">Open Resource</a> : resource.hasControlledFile ? <a href={`/api/student/session-resources/${resource.id}/download`} className="font-semibold text-amber-800">Open Material</a> : null}<Link href={`/student/sessions/${resource.sessionId}#resources`} className="font-semibold text-amber-800 underline-offset-4 hover:underline">View Class Session</Link></div></li>)}</ul> : <EmptyState>No learning resources are currently available.</EmptyState>}</StudentPanel><StudentPanel title="Course Recordings" description="Recordings currently available for this course.">{detail.recordings.length ? <ul className="space-y-3">{detail.recordings.map((recording) => <li key={recording.id} className="rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-amber-700">{recording.sessionTitle}</p><h3 className="mt-1 font-semibold text-[#071327]">{recording.title}</h3><p className="mt-1 text-sm text-slate-600">{formatStudentDate(recording.sessionDate)}{formatDuration(recording.durationSeconds) ? ` · ${formatDuration(recording.durationSeconds)}` : ""}</p><Link href={`/student/sessions/${recording.sessionId}#recording-${recording.id}`} className="mt-3 inline-block text-sm font-semibold text-amber-800 underline-offset-4 hover:underline">Open Recording</Link></li>)}</ul> : <EmptyState>No class recordings are currently available.</EmptyState>}</StudentPanel></div>
  </div>;
}

function HeaderItem({ label, value }: { label: string; value: string }) {
  return <div><dt className="text-xs font-semibold uppercase tracking-[0.12em] text-white/60">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>;
}
