import Link from "next/link";

import { AdminShell } from "@/components/admin/AdminShell";
import { requireAdmin } from "@/lib/adminAuth";
import { attendanceStatusLabels, deliveryRouteLabels, type AttendanceStatus, type DeliveryRoute } from "@/lib/lms/attendance";
import { fetchAttendanceDashboard } from "@/lib/lms/attendanceService";
import { requireLmsAdminClient } from "@/lib/lms/adminData";
import { fetchSessionOptions } from "@/lib/lms/sessionData";
import { AssignMakeupButton } from "@/components/admin/AssignMakeupButton";

function object(value: unknown): Record<string, unknown> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function relation(value: unknown) { return Array.isArray(value) ? object(value[0]) : object(value); }

export default async function AdminAttendancePage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  await requireAdmin(); const search = await searchParams;
  const value = (key: string) => typeof search[key] === "string" ? search[key] as string : undefined;
  const supabase = requireLmsAdminClient();
  const [data, options, sessions] = await Promise.all([
    fetchAttendanceDashboard(supabase, { cohort: value("cohort"), course: value("course"), session: value("session"), facilitator: value("facilitator"), route: value("route"), status: value("status"), student: value("student"), from: value("from"), to: value("to") }),
    fetchSessionOptions(supabase),
    supabase.from("class_sessions").select("id, title").order("scheduled_start_at", { ascending: false, nullsFirst: false }).limit(500),
  ]);
  const cohorts = new Map<string, string>(); const courses = new Map<string, string>();
  for (const raw of options.offerings) { const offering = object(raw); const cohort = relation(offering.cohorts); const course = relation(offering.courses); if (typeof cohort.id === "string") cohorts.set(cohort.id, `${cohort.code} · ${cohort.name}`); if (typeof course.id === "string") courses.set(course.id, `${course.code} · ${course.title}`); }
  return <AdminShell title="Attendance" description="Finalized attendance, pending review, absence units, and route-level evidence across current sessions.">
    <form className="mb-6 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 md:grid-cols-2 xl:grid-cols-4"><input name="student" defaultValue={value("student")} placeholder="Student name or number" className="min-h-11 rounded-lg border border-slate-300 px-3" /><select name="cohort" defaultValue={value("cohort") ?? ""} className="min-h-11 rounded-lg border border-slate-300 px-3"><option value="">All cohorts</option>{[...cohorts].map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select><select name="course" defaultValue={value("course") ?? ""} className="min-h-11 rounded-lg border border-slate-300 px-3"><option value="">All courses</option>{[...courses].map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select><select name="session" defaultValue={value("session") ?? ""} className="min-h-11 rounded-lg border border-slate-300 px-3"><option value="">All sessions</option>{(sessions.data ?? []).map((session) => <option key={session.id} value={session.id}>{session.title}</option>)}</select><select name="facilitator" defaultValue={value("facilitator") ?? ""} className="min-h-11 rounded-lg border border-slate-300 px-3"><option value="">All facilitators</option>{options.facilitators.map((facilitator) => <option key={facilitator.id} value={facilitator.id}>{facilitator.display_name}</option>)}</select><select name="route" defaultValue={value("route") ?? ""} className="min-h-11 rounded-lg border border-slate-300 px-3"><option value="">All routes</option>{Object.entries(deliveryRouteLabels).map(([route, label]) => <option key={route} value={route}>{route} · {label}</option>)}</select><select name="status" defaultValue={value("status") ?? ""} className="min-h-11 rounded-lg border border-slate-300 px-3"><option value="">All statuses</option>{Object.entries(attendanceStatusLabels).map(([status, label]) => <option key={status} value={status}>{label}</option>)}</select><div className="grid grid-cols-2 gap-2"><input type="date" name="from" aria-label="Attendance date from" defaultValue={value("from")} className="min-h-11 rounded-lg border border-slate-300 px-2" /><input type="date" name="to" aria-label="Attendance date to" defaultValue={value("to")} className="min-h-11 rounded-lg border border-slate-300 px-2" /></div><button className="min-h-11 rounded-lg bg-[#0b315c] px-4 font-semibold text-white xl:col-span-4">Apply attendance filters</button></form>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Total Required Attendance Records", data.summary.total], ["Present", data.summary.present], ["Late", data.summary.late], ["Partial", data.summary.partial], ["Absent", data.summary.absent], ["Excused Absence", data.summary.excused], ["Pending Verification", data.summary.pendingVerification], ["Recorded Verification Pending", data.summary.recordedPending]].map(([label, number]) => <div key={String(label)} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-600">{label}</p><p className="mt-2 text-3xl font-semibold text-[#071327]">{number}</p></div>)}</div>
    <div className="mt-6 overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-600"><tr><th className="px-4 py-3">Student</th><th className="px-4 py-3">Session</th><th className="px-4 py-3">Course / Cohort</th><th className="px-4 py-3">Date</th><th className="px-4 py-3">Delivery Route</th><th className="px-4 py-3">Attendance Status</th><th className="px-4 py-3">Absence Weight</th><th className="px-4 py-3">Finalized?</th></tr></thead><tbody className="divide-y divide-slate-200">{data.rows.map((row) => { const session = relation(row.class_sessions); const offering = relation(session.cohort_courses); const course = relation(offering.courses); const cohort = relation(offering.cohorts); const student = relation(relation(relation(row.course_enrollments).student_enrollments).students); return <tr key={row.id}><td className="px-4 py-3"><p className="font-semibold text-[#071327]">{String(student.preferred_name || student.legal_name || "Student")}</p><p className="text-xs text-slate-500">{String(student.student_number || "")}</p></td><td className="px-4 py-3"><Link href={`/admin/sessions/${session.id}/attendance`} className="font-semibold text-[#0b315c] hover:underline">{String(session.title)}</Link></td><td className="px-4 py-3">{String(course.code || "")}<p className="text-xs text-slate-500">{String(cohort.code || "")}</p></td><td className="px-4 py-3">{typeof session.scheduled_start_at === "string" ? new Date(session.scheduled_start_at).toLocaleDateString("en-NG") : "Not scheduled"}</td><td className="px-4 py-3">{deliveryRouteLabels[row.assigned_delivery_route as DeliveryRoute]}</td><td className="px-4 py-3">{attendanceStatusLabels[row.attendance_status as AttendanceStatus]}{row.attendance_status === "absent" ? <AssignMakeupButton attendanceId={row.id} /> : null}</td><td className="px-4 py-3">{Number(row.absence_weight ?? 0)}</td><td className="px-4 py-3">{row.finalized_at ? "Yes" : "No"}</td></tr>; })}</tbody></table>{!data.rows.length ? <p className="p-8 text-center text-sm text-slate-600">No attendance records match these filters.</p> : null}</div>
  </AdminShell>;
}
