"use client";

import Link from "next/link";
import { useState } from "react";
import type { fetchFacilitatorSession } from "@/lib/lms/facilitatorSessions";
import { institutionalValueLabel } from "@/lib/lms/presentation";
type RecordData = Awaited<ReturnType<typeof fetchFacilitatorSession>>;
function object(value: unknown) { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function relation(value: unknown) { return Array.isArray(value) ? object(value[0]) : object(value); }
function text(value: unknown) { return typeof value === "string" ? value : null; }
function lines(value: unknown) { return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string").join("\n") : ""; }
export function FacultySessionRecord({ initialRecord }: { initialRecord: RecordData }) { const [record] = useState(initialRecord); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const session = object(record.session), offering = relation(session.cohort_courses), course = relation(offering.courses), cohort = relation(offering.cohorts), summary = record.summary ? object(record.summary) : null; async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const response = await fetch(`/api/facilitator/sessions/${text(session.id)}/summary`, { method: summary ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); const body = await response.json(); setBusy(false); if (!response.ok) return setMessage(body.message || "Summary draft could not be saved."); setMessage("Summary draft saved."); window.location.reload(); }
  return <div className="space-y-6"><div className="flex flex-wrap gap-4"><Link href="/facilitator/sessions" className="text-sm font-semibold text-[var(--realm-gold-soft)]">Back to assigned sessions</Link><Link href={`/facilitator/sessions/${text(session.id)}/attendance`} className="text-sm font-semibold text-[var(--realm-gold-soft)]">Open attendance roster</Link></div>{message ? <p className="rounded-xl border border-amber-300/25 bg-amber-300/10 p-4 text-sm text-amber-100">{message}</p> : null}<section className="rounded-2xl border border-white/10 bg-white/[0.055] p-6"><p className="text-xs font-semibold uppercase tracking-wider text-[var(--realm-gold-soft)]">{text(course.code)} · {text(cohort.code)}</p><h2 className="mt-3 text-2xl font-semibold">{text(course.title)}</h2><dl className="mt-6 grid gap-4 sm:grid-cols-2"><Item label="Schedule" value={text(session.scheduled_start_at) ? new Date(text(session.scheduled_start_at)!).toLocaleString("en-NG", { dateStyle: "long", timeStyle: "short" }) : "Not scheduled"} /><Item label="Timezone" value={text(session.timezone) || "Africa/Lagos"} /><Item label="Delivery" value={humanize(text(session.delivery_mode))} /><Item label="Status" value={humanize(text(session.session_status))} /><Item label="Live class">{text(session.live_join_url) ? <a href={text(session.live_join_url)!} target="_blank" rel="noreferrer" className="text-[var(--realm-gold-soft)]">Open class link</a> : "Not set"}</Item><Item label="Location" value={text(session.physical_location) || "Not set"} /></dl></section>
    <section className="rounded-2xl border border-white/10 bg-white/[0.055] p-6"><h2 className="text-xl font-semibold">Class summary</h2><p className="mt-2 text-sm text-[var(--realm-muted)]">Faculty may create and edit drafts. Publishing and archived-summary changes remain with administrators.</p>{summary && summary.summary_status !== "draft" ? <div className="mt-5 rounded-xl border border-white/10 p-4"><p className="font-semibold capitalize">{humanize(text(summary.summary_status))} · Version {String(summary.version_number)}</p><p className="mt-2 text-sm text-[var(--realm-muted)]">This summary is read-only in the Faculty Portal.</p></div> : <form onSubmit={save} className="mt-6 grid gap-4 md:grid-cols-2"><Input name="title" label="Summary title" value={summary ? text(summary.title) : text(session.title)} /><List name="learning_objectives" label="Learning objectives" value={summary?.learning_objectives} /><List name="key_teaching_points" label="Key teaching points" value={summary?.key_teaching_points} /><List name="key_scriptures_references" label="Key Scriptures / references" value={summary?.key_scriptures_references} /><List name="important_concepts" label="Important concepts" value={summary?.important_concepts} /><List name="practical_applications" label="Practical applications" value={summary?.practical_applications} /><List name="action_points" label="Assignments / action points" value={summary?.action_points} /><List name="recommended_resources" label="Recommended resources" value={summary?.recommended_resources} /><label className="text-sm font-semibold md:col-span-2">Additional notes<textarea name="additional_notes" defaultValue={summary ? text(summary.additional_notes) || "" : ""} rows={4} className="mt-2 block w-full rounded-xl border border-white/15 bg-[#050d1c]/60 p-3" /></label><label className="text-sm font-semibold md:col-span-2">Revision note<textarea name="change_note" rows={2} className="mt-2 block w-full rounded-xl border border-white/15 bg-[#050d1c]/60 p-3" /></label><button disabled={busy} className="rounded-full bg-[var(--realm-gold)] px-5 py-3 text-sm font-semibold text-[#071327] disabled:opacity-50 md:col-span-2">{busy ? "Saving…" : summary ? "Save draft revision" : "Create summary draft"}</button></form>}</section>
    <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-white/10 bg-white/[0.055] p-6"><h2 className="text-xl font-semibold">Resources</h2>{record.resources.length === 0 ? <p className="mt-4 text-sm text-[var(--realm-muted)]">No resources are available for this session.</p> : <ul className="mt-4 space-y-3">{record.resources.map((raw) => { const item = object(raw); return <li key={text(item.id)!} className="rounded-xl border border-white/10 p-4"><strong>{text(item.title)}</strong><p className="mt-1 text-sm text-[var(--realm-muted)]">{humanize(text(item.resource_type))}</p>{text(item.external_url) ? <a href={text(item.external_url)!} target="_blank" rel="noreferrer" className="mt-2 inline-block text-sm text-[var(--realm-gold-soft)]">Open resource</a> : null}</li>; })}</ul>}</section><section className="rounded-2xl border border-white/10 bg-white/[0.055] p-6"><h2 className="text-xl font-semibold">Recording metadata</h2>{record.recordings.length === 0 ? <p className="mt-4 text-sm text-[var(--realm-muted)]">No recording has been added.</p> : <ul className="mt-4 space-y-3">{record.recordings.map((raw) => { const item = object(raw); return <li key={text(item.id)!} className="rounded-xl border border-white/10 p-4"><strong>{text(item.title)}</strong><p className="mt-1 text-sm capitalize text-[var(--realm-muted)]">{humanize(text(item.recording_status))} · {humanize(text(item.provider))}</p><p className="mt-1 text-xs text-[var(--realm-slate)]">Quality checked: {item.quality_checked ? "Yes" : "No"}</p></li>; })}</ul>}<p className="mt-4 text-xs text-[var(--realm-slate)]">Recording metadata does not indicate attendance or completion.</p></section></div>
  </div>; }
function Item({ label, value, children }: { label: string; value?: string; children?: React.ReactNode }) { return <div><dt className="text-xs font-semibold uppercase tracking-wider text-[var(--realm-gold-soft)]">{label}</dt><dd className="mt-2">{children || value}</dd></div>; }
function Input({ name, label, value }: { name: string; label: string; value: string | null }) { return <label className="text-sm font-semibold">{label}<input name={name} defaultValue={value || ""} className="mt-2 block w-full rounded-xl border border-white/15 bg-[#050d1c]/60 px-3 py-2" /></label>; }
function List({ name, label, value }: { name: string; label: string; value: unknown }) { return <label className="text-sm font-semibold">{label} <span className="font-normal text-[var(--realm-slate)]">(one per line)</span><textarea name={name} defaultValue={lines(value)} rows={5} className="mt-2 block w-full rounded-xl border border-white/15 bg-[#050d1c]/60 p-3" /></label>; }
function humanize(value: string | null) { return institutionalValueLabel(value, "Not Set"); }
