import Link from "next/link";

import { announcementIsPinned } from "@/lib/lms/institutionalAnnouncements";

type Announcement = { id: string; title: string; message: string; published_at: string | null; pinned_until: string | null; call_to_action_label: string | null; call_to_action_url: string | null };

export function InstitutionalAnnouncements({ announcements, variant = "light" }: { announcements: Announcement[]; variant?: "light" | "dark" }) {
  if (!announcements.length) return null;
  const ordered = [...announcements].sort((a, b) => Number(announcementIsPinned(b)) - Number(announcementIsPinned(a)) || String(b.published_at).localeCompare(String(a.published_at)));
  return <section aria-labelledby="current-announcements-title" className="space-y-3"><h2 id="current-announcements-title" className={`text-xl font-semibold ${variant === "dark" ? "text-white" : "text-[#071327]"}`}>Current Announcements</h2>{ordered.map((announcement) => { const pinned = announcementIsPinned(announcement); return <article key={announcement.id} className={variant === "dark" ? `rounded-2xl border p-5 ${pinned ? "border-[var(--realm-gold)]/60 bg-[var(--realm-gold)]/10" : "border-white/10 bg-white/[0.055]"}` : `rounded-2xl border bg-white p-5 ${pinned ? "border-amber-400 shadow-sm" : "border-slate-200"}`}><div className="flex flex-wrap items-start justify-between gap-3"><h3 className={`font-semibold ${variant === "dark" ? "text-white" : "text-[#071327]"}`}>{announcement.title}</h3>{pinned ? <span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-semibold text-amber-900">Pinned</span> : null}</div><p className={`mt-3 whitespace-pre-line text-sm leading-6 ${variant === "dark" ? "text-white/75" : "text-slate-700"}`}>{announcement.message}</p>{announcement.published_at ? <p className={`mt-3 text-xs ${variant === "dark" ? "text-white/50" : "text-slate-500"}`}>Published {new Intl.DateTimeFormat("en-NG", { dateStyle: "medium", timeZone: "Africa/Lagos" }).format(new Date(announcement.published_at))}</p> : null}{announcement.call_to_action_label && announcement.call_to_action_url ? <Link href={announcement.call_to_action_url} target={announcement.call_to_action_url.startsWith("http") ? "_blank" : undefined} rel={announcement.call_to_action_url.startsWith("http") ? "noopener noreferrer" : undefined} className={`mt-4 inline-flex rounded-lg px-4 py-2 text-sm font-semibold ${variant === "dark" ? "bg-[var(--realm-gold)] text-[#071327]" : "bg-[#071327] text-white"}`}>{announcement.call_to_action_label}</Link> : null}</article>; })}</section>;
}
