"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";

async function request(url: string, body?: Record<string, unknown>) { const response = await fetch(url, { method: "POST", headers: body ? { "Content-Type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.message || "The request could not be completed."); }

export function StandingAcknowledgeButton({ type, id }: { type: "warning" | "plan"; id: string }) { const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); async function act() { setBusy(true); try { await request(type === "warning" ? `/api/student/warnings/${id}/acknowledge` : `/api/student/recovery-plans/${id}/acknowledge`); setMessage("Acknowledgement recorded."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Acknowledgement failed."); } finally { setBusy(false); } } return <div className="mt-3"><button disabled={busy} onClick={act} className="rounded-lg border border-[var(--realm-gold)]/60 px-3 py-2 text-xs font-semibold text-[var(--realm-gold-soft)] disabled:opacity-50">{busy ? "Saving…" : "Acknowledge"}</button>{message ? <p className="mt-2 text-xs text-white/65">{message}</p> : null}</div>; }

export function StudentResponseForm({ type, id }: { type: "warning" | "review"; id: string }) { const router = useRouter(); const [response, setResponse] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); try { await request(type === "warning" ? `/api/student/warnings/${id}/respond` : `/api/student/review-cases/${id}/respond`, { response }); setResponse(""); setMessage("Your response has been submitted for review."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Response could not be saved."); } finally { setBusy(false); } } return <form onSubmit={submit} className="mt-4"><textarea value={response} onChange={(event) => setResponse(event.target.value)} required maxLength={5000} rows={4} className="w-full rounded-xl border border-white/15 bg-white/[0.06] p-3 text-sm text-white placeholder:text-white/45" placeholder="Your factual response or relevant context" /><button disabled={busy || !response.trim()} className="mt-2 rounded-lg bg-[var(--realm-gold)] px-4 py-2 text-xs font-semibold text-[#071327] disabled:opacity-50">Submit Response</button>{message ? <p className="mt-2 text-xs text-white/65">{message}</p> : null}</form>; }

export function MentorFollowupForm({ studentEnrollmentId }: { studentEnrollmentId: string }) { const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const values = Object.fromEntries(new FormData(event.currentTarget)); try { await request(`/api/mentor/students/${studentEnrollmentId}/followups`, values); setMessage("Follow-up recorded."); event.currentTarget.reset(); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Follow-up could not be recorded."); } finally { setBusy(false); } } const field = "min-h-11 w-full rounded-xl border border-white/15 bg-white/[0.06] px-3 text-sm text-white"; return <form onSubmit={submit} className="grid gap-3"><select name="contact_status" className={field}>{["attempted", "contacted", "no_response", "rescheduled", "completed"].map((value) => <option key={value} className="text-slate-950">{value}</option>)}</select><input name="contact_method" required placeholder="Contact method" className={field} /><input name="contacted_at" type="datetime-local" className={field} /><textarea name="contact_summary" maxLength={1500} rows={3} placeholder="Minimal operational summary—not a counselling transcript" className={`${field} py-3`} /><textarea name="agreed_next_action" maxLength={1000} rows={2} placeholder="Agreed next action" className={`${field} py-3`} /><input name="next_followup_at" type="datetime-local" className={field} /><button disabled={busy} className="rounded-xl bg-[var(--realm-gold)] px-4 py-2.5 font-semibold text-[#071327] disabled:opacity-50">Record Follow-Up</button>{message ? <p className="text-xs text-white/65">{message}</p> : null}</form>; }

export function CompleteRecoveryActionButton({ studentEnrollmentId, actionId, linked }: { studentEnrollmentId: string; actionId: string; linked: boolean }) { const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); async function complete() { const note = linked ? "Verified from linked academic record." : window.prompt("Concise completion note"); if (!note) return; setBusy(true); try { await request(`/api/mentor/students/${studentEnrollmentId}/recovery-plan-actions`, { action_id: actionId, completion_note: note }); setMessage("Action completion recorded."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Action could not be completed."); } finally { setBusy(false); } } return <div><button disabled={busy} onClick={complete} className="rounded-lg border border-[var(--realm-gold)]/60 px-3 py-2 text-xs font-semibold text-[var(--realm-gold-soft)]">Verify Completion</button>{message ? <p className="mt-1 text-xs text-white/65">{message}</p> : null}</div>; }

export function SupportReferralForm({ studentEnrollmentId }: { studentEnrollmentId: string }) { const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const values = Object.fromEntries(new FormData(event.currentTarget)); try { await request(`/api/mentor/students/${studentEnrollmentId}/support-referrals`, values); setMessage("Support referral recorded for authorised follow-up."); event.currentTarget.reset(); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Referral could not be created."); } finally { setBusy(false); } } const field = "min-h-11 w-full rounded-xl border border-white/15 bg-white/[0.06] px-3 text-sm text-white"; return <form onSubmit={submit} className="grid gap-3"><select name="referral_category" className={field}>{["academic_support", "pastoral_support", "wellbeing_support", "accessibility_support", "technical_support", "administrative_support"].map((value) => <option key={value} className="text-slate-950">{value}</option>)}</select><input name="referred_to" required maxLength={180} placeholder="Authorised support destination" className={field} /><textarea name="referral_reason_summary" required maxLength={1200} rows={3} placeholder="Minimal reason only—do not store clinical, legal, or counselling case notes" className={`${field} py-3`} /><button disabled={busy} className="rounded-xl border border-[var(--realm-gold)]/60 px-4 py-2.5 font-semibold text-[var(--realm-gold-soft)]">Recommend Support Referral</button>{message ? <p className="text-xs text-white/65">{message}</p> : null}</form>; }
