import Link from "next/link";

import { AdminShell } from "@/components/admin/AdminShell";
import { EmptyState, StatusBadge } from "@/components/admin/LmsUi";
import { requireAdmin } from "@/lib/adminAuth";
import { humanize } from "@/lib/lms/adminConstants";
import { fetchAdminCourses, requireLmsAdminClient } from "@/lib/lms/adminData";

function val(value: string | string[] | undefined) { return typeof value === "string" ? value : ""; }
export default async function AdminCoursesPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  await requireAdmin(); const params = await searchParams; const category = val(params.category); const route = val(params.route); const pathway = val(params.pathway); const state = val(params.state); let courses = await fetchAdminCourses(requireLmsAdminClient());
  courses = courses.filter((course) => (!category || course.course_category === category) && (!route || course.discipleship_route === route) && (!pathway || course.skill_pathway === pathway) && (!state || String(course.active) === state));
  return <AdminShell title="Courses" description="Manage the approved course catalogue, operational schedules, learning outcomes, and assessed evidence."><form className="mb-6 flex flex-wrap gap-3 rounded-2xl border border-slate-200 bg-white p-4"><select name="category" defaultValue={category} className="rounded-xl border border-slate-300 px-3 py-2 text-sm"><option value="">All categories</option><option value="discipleship">Discipleship</option><option value="skill">Skill</option><option value="capstone">Capstone</option></select><select name="route" defaultValue={route} className="rounded-xl border border-slate-300 px-3 py-2 text-sm"><option value="">All routes</option><option value="foundational">Foundational</option><option value="advanced">Advanced</option></select><select name="pathway" defaultValue={pathway} className="rounded-xl border border-slate-300 px-3 py-2 text-sm"><option value="">All pathways</option><option value="web_development">Web Development</option><option value="cybersecurity_foundations">Cybersecurity</option></select><select name="state" defaultValue={state} className="rounded-xl border border-slate-300 px-3 py-2 text-sm"><option value="">Active and inactive</option><option value="true">Active</option><option value="false">Inactive</option></select><button className="rounded-xl bg-[#071327] px-4 py-2 text-sm font-semibold text-white">Apply</button><Link href="/admin/courses" className="rounded-xl border border-slate-300 px-4 py-2 text-sm font-semibold">Clear</Link></form>{courses.length === 0 ? <EmptyState title="No courses found" detail="No catalogue courses match the selected filters." /> : <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Code / title</th><th>Category</th><th>Route / pathway</th><th>Sequence</th><th>Offerings</th><th>Enrolments</th><th>Status</th></tr></thead><tbody className="divide-y divide-slate-100">{courses.map((course) => <tr key={course.id}><td className="px-4 py-4"><Link href={`/admin/courses/${course.id}`} className="font-semibold text-amber-800 hover:underline">{course.code}</Link><p>{course.title}</p></td><td>{humanize(course.course_category)}</td><td>{humanize(course.discipleship_route || course.skill_pathway)}</td><td>{course.sequence_number ?? "—"}</td><td>{course.offering_count}</td><td>{course.enrollment_count}</td><td><StatusBadge value={course.active ? "active" : "inactive"} /></td></tr>)}</tbody></table></div>}</AdminShell>;
}
