import { notFound } from "next/navigation";

import { CheckpointForm, RecordingPlayer, UnsupportedRecordingAccess } from "@/components/student/RecordingPlayer";
import { DataCard, formatStudentDate, humanizeStudentValue, StudentPanel } from "@/components/student/StudentUi";
import { requireRole } from "@/lib/lms/auth";
import { requireLmsAdminClient } from "@/lib/lms/adminData";
import { recordingPurposeStudentCopy } from "@/lib/lms/recording";
import { getStudentRecordingAssignment } from "@/lib/lms/recordingData";
import { evaluateRecordedLearningAssignment, resolveStudentRecordingAssignment } from "@/lib/lms/recordingService";

export default async function StudentRecordingPage({ params }: { params: Promise<{ assignmentId: string }> }) {
  const { user } = await requireRole("student");
  const { assignmentId } = await params;
  const trustedClient = requireLmsAdminClient();
  try {
    await resolveStudentRecordingAssignment(trustedClient, user.id, assignmentId);
    await evaluateRecordedLearningAssignment(trustedClient, assignmentId, { actorLabel: "System", actorUserId: user.id });
  } catch { notFound(); }
  const detail = await getStudentRecordingAssignment(user.id, assignmentId);
  if (!detail) notFound();
  const isRevision = detail.purposeCode === "REV";
  const isZoomManual = detail.recording.provider === "zoom" && detail.recording.trackingMode === "manual_review";
  const watchRequired = Number(detail.effectiveRequirements.minWatchPercentage ?? 85);
  const required = isRevision ? [] : detail.requirements.filter((item) => item.required);
  const purposeCopy = recordingPurposeStudentCopy[detail.purposeCode];
  const playerCheckpoints = isRevision || isZoomManual ? [] : detail.checkpoints.map((checkpoint) => ({ id: String(checkpoint.id), title: String(checkpoint.title), position_seconds: checkpoint.position_seconds === null ? null : Number(checkpoint.position_seconds), position_percentage: checkpoint.position_percentage === null ? null : Number(checkpoint.position_percentage), is_required: Boolean(checkpoint.is_required) }));

  return <div className="space-y-6">
    <header className="rounded-3xl bg-[linear-gradient(135deg,#092648,#0e3a68)] p-6 text-white"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[var(--realm-gold-soft)]">{detail.course.code} · {purposeCopy.heading}</p><h1 className="mt-2 text-3xl font-semibold">{detail.recording.title}</h1><p className="mt-2 text-white/70">{detail.session.title}</p><p className="mt-4 max-w-3xl text-sm leading-6 text-white/80">{purposeCopy.description}</p></header>
    <StudentPanel title="Recording">
      {detail.accessState === "upcoming" ? <div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-amber-950">This recording becomes available {formatStudentDate(detail.availableAt, true)}.</div> : detail.accessState === "expired" ? <div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-amber-950">This recording access window has expired. Your historical progress remains preserved.</div> : detail.recording.embedUrl ? <RecordingPlayer assignmentId={detail.id} embedUrl={detail.recording.embedUrl} durationSeconds={detail.recording.durationSeconds} checkpoints={playerCheckpoints} completedCheckpointIds={isRevision ? [] : detail.completedCheckpointIds} /> : <div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-amber-950"><h2 className="font-semibold">{isRevision ? "Automatic revision progress unavailable" : "Progress requires staff review"}</h2><p className="mt-2 text-sm leading-6">Automated viewing progress is not available for this recording. Opening it does not fabricate a viewing percentage or attendance result.{isRevision ? " This does not create an academic requirement or review obligation." : ""}</p>{detail.recording.externalUrl ? <UnsupportedRecordingAccess assignmentId={detail.id} externalUrl={detail.recording.externalUrl} /> : null}</div>}
    </StudentPanel>
    {detail.progress.integrityStatus !== "clear" ? <p role="status" className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-950">{isRevision ? "A technical note is attached to this optional revision activity. It does not change your attendance or learning completion." : "Your learning activity is under review. REALMS may contact you for clarification."}</p> : null}
    {isRevision ? <StudentPanel title="Revision recording"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><DataCard label="Viewing" value="Optional" /><DataCard label="Minimum watch" value="No minimum watch requirement" /><DataCard label="Checkpoints" value="No required checkpoints" /><DataCard label="Deadline" value="No academic deadline" /></div>{detail.progress.watchPercentage > 0 && !isZoomManual ? <p className="mt-5 text-sm text-slate-600">Revision viewing progress: {Math.floor(detail.progress.watchPercentage)}% measured. This is informational only.</p> : null}</StudentPanel> : <StudentPanel title="My requirement status"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><DataCard label={isZoomManual ? "Zoom viewing evidence" : "Watch"} value={isZoomManual ? "Manual staff verification required" : `${Math.floor(detail.progress.watchPercentage)}% of required ${watchRequired}%`} /><DataCard label="Checkpoints" value={`${detail.progress.checkpointRequirementMet ? "Completed" : "Pending"} · ${Number(detail.effectiveRequirements.requiredCheckpointCount ?? 2)} required`} /><DataCard label="Verification state" value={humanizeStudentValue(detail.displayStatus)} /><DataCard label="Deadline" value={detail.dueAt ? formatStudentDate(detail.dueAt, true) : "No deadline"} /></div>{isZoomManual ? <p className="mt-5 rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm leading-6 text-blue-950">Automatic playback measurement is unavailable for this Zoom recording. Your required learning evidence will be reviewed. Zoom evidence alone does not verify attendance or make-up completion.</p> : null}<ul className="mt-5 grid gap-3 sm:grid-cols-2">{required.map((item) => <li key={item.id} className="rounded-xl border border-slate-200 p-4"><span className="font-semibold text-[#071327]">{item.type === "watch" && isZoomManual ? "Zoom viewing evidence" : humanizeStudentValue(item.type)}</span><span className="mt-1 block text-sm text-slate-600">{humanizeStudentValue(item.status)}</span>{["quiz", "practical"].includes(item.type) && item.status !== "satisfied" ? <span className="mt-1 block text-xs text-slate-500">This assessment is not yet available.</span> : null}</li>)}</ul></StudentPanel>}
    {!isRevision && detail.checkpoints.length ? <StudentPanel title="Required checkpoints" description={isZoomManual ? "Answer each teaching-content question in sequence. Checkpoint answers and Zoom viewing evidence are reviewed together; neither verifies attendance by itself." : "Long-form checkpoint responses remain for human review; they are not automatically scored."}><div className="space-y-4">{detail.checkpoints.map((checkpoint) => <CheckpointForm key={String(checkpoint.id)} assignmentId={detail.id} checkpoint={checkpoint} />)}</div></StudentPanel> : !isRevision && required.some((item) => item.type === "checkpoints") ? <p className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-950">Recorded verification cannot complete because required checkpoints have not been configured. REALMS staff have been alerted by the requirement state.</p> : null}
    <StudentPanel title="Attendance and learning remain separate"><div className="grid gap-3 sm:grid-cols-2"><DataCard label="Attendance" value={detail.attendance ? humanizeStudentValue(detail.attendance.attendance_status) : "Pending"} /><DataCard label="Learning completion" value={humanizeStudentValue(detail.completionStatus ?? "not_started")} /></div>{detail.purposeCode === "REV" ? <p className="mt-4 text-sm leading-6 text-slate-600">Revision progress does not create or change attendance, does not replace existing live learning completion, and cannot satisfy a separate make-up requirement.</p> : ["MU-E", "MU-U"].includes(detail.purposeCode) ? <p className="mt-4 text-sm leading-6 text-slate-600">Completing this make-up satisfies the required missed learning separately. Your original attendance history remains unchanged.</p> : ["RP", "DR-E"].includes(detail.purposeCode) ? <p className="mt-4 text-sm leading-6 text-slate-600">Official recorded attendance is created only after all required evidence is verified by the recorded-learning evaluator.</p> : null}</StudentPanel>
  </div>;
}
