import type { Metadata } from "next";
import { Check, MonitorPlay } from "lucide-react";

import { PageHero } from "@/components/layout/PageHero";
import { PageShell } from "@/components/layout/PageShell";
import { PrimaryButton, SecondaryButton } from "@/components/ui/Button";
import { Testimonials } from "@/components/sections/Testimonials";
import { certificateNote, cohortPricing, discoveryAudiences, discoveryCore, discoveryLearningFormat, discoverySkillPathways, discoveryStudentReceives } from "@/lib/constants";

export const metadata: Metadata = { title: "REALMS School of Discovery | Discipleship & Skill Pathways", description: "Explore the foundational REALMS Institute school combining discipleship and theology formation with Web Development or Cybersecurity Foundations." };

export default function DiscoveryPage() {
  return <PageShell>
    <PageHero eyebrow="Next Cohort" title="REALMS School of Discovery" subtitle="The foundational school of REALMS Institute, combining Christian discipleship and theology formation with one selected practical skill pathway." breadcrumbs={[{ label: "Home", href: "/" }, { label: "Schools", href: "/schools" }, { label: "School of Discovery" }]} />
    <LightSection eyebrow="Overview" title="A Foundation for Faithful Service"><p className="max-w-4xl text-lg leading-8 text-slate-600">REALMS School of Discovery is the foundational school of REALMS Institute. It helps students grow in Christ, understand identity and calling, build spiritual disciplines, and begin practical skill training for usefulness in their generation.</p></LightSection>
    <section aria-labelledby="model-title" className="bg-[#071327] px-5 py-20 text-white md:px-8 md:py-28"><div className="mx-auto max-w-7xl"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[var(--realm-gold-soft)]">Two-Fold Formation Model</p><h2 id="model-title" className="mt-4 text-3xl font-semibold tracking-tight md:text-5xl">Formation in God. Equipping for your field.</h2><div className="mt-10 grid gap-6 lg:grid-cols-2"><ListCard title="1. Discipleship & Theology Formation" items={discoveryCore} /><ListCard title="2. Practical Skill Pathway" items={discoverySkillPathways} /></div><p className="mt-6 max-w-4xl rounded-2xl border border-white/10 bg-white/[0.04] p-5 text-sm leading-7 text-white/70">For the next cohort, students may choose Web Development or Cybersecurity Foundations. Cloud Computing and other pathways may be introduced in future cohorts as the institute grows.</p></div></section>
    <LightSection eyebrow="What You Will Receive" title="Clear, Truthful Learning Outcomes"><List items={discoveryStudentReceives} /><p className="mt-6 text-sm leading-6 text-slate-500">{certificateNote}</p></LightSection>
    <Testimonials id="discovery-testimonials" showAll />
    <section aria-labelledby="audience-title" className="bg-white px-5 py-20 md:px-8 md:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#8b641c]">Who It Is For</p><h2 id="audience-title" className="mt-4 text-3xl font-semibold tracking-tight text-[#071327] md:text-5xl">For those ready to learn and grow.</h2><p className="mt-5 max-w-xl leading-7 text-slate-600">REALMS Institute primarily serves believers who desire deeper formation in God and practical equipping for their field of assignment. Those who are new to faith or exploring Christianity may begin through the foundational teachings of the School of Discovery.</p><List items={discoveryAudiences} /></div><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#8b641c]">Learning Format</p><h2 className="mt-4 text-3xl font-semibold tracking-tight text-[#071327] md:text-5xl">Structured for participation.</h2><List items={[...discoveryLearningFormat.slice(0, 4), "Assessments", "Skill pathway training"]} icon={MonitorPlay} /></div></div></section>
    <LightSection eyebrow="Registration and Cohort Participation Fee" title="Choose Physical or Online"><div className="grid gap-4 md:grid-cols-3"><PriceCard label="Physical" value={cohortPricing.physical.display} detail="For students attending onsite" /><PriceCard label="Online Nigeria" value={cohortPricing.onlineNigeria.display} detail="For online students in Nigeria" /><PriceCard label="International Online" value={cohortPricing.internationalOnline.display} detail="For online students outside Nigeria" /></div></LightSection>
    <section className="bg-[#f7f5ef] px-5 py-20 md:px-8"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-7 rounded-3xl border border-[#d7aa45]/30 bg-[#071327] p-7 text-white md:flex-row md:items-center md:p-12"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-[var(--realm-gold-soft)]">Take the Next Step</p><h2 className="mt-3 text-3xl font-semibold">Begin your formation journey.</h2></div><div className="flex flex-col gap-3 sm:flex-row"><PrimaryButton href="/register" showIcon>Apply for Next Cohort</PrimaryButton><SecondaryButton href="/contact">Ask a Question</SecondaryButton></div></div></section>
  </PageShell>;
}

function LightSection({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) { return <section className="bg-[#f7f5ef] px-5 py-20 md:px-8 md:py-28"><div className="mx-auto max-w-7xl"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#8b641c]">{eyebrow}</p><h2 className="mt-4 mb-7 text-3xl font-semibold tracking-tight text-[#071327] md:text-5xl">{title}</h2>{children}</div></section>; }
function ListCard({ title, items }: { title: string; items: readonly string[] }) { return <article className="rounded-3xl border border-white/12 bg-white/[0.055] p-6 md:p-8"><h3 className="text-2xl font-semibold">{title}</h3><List items={items} dark /></article>; }
function List({ items, dark = false, icon: Icon = Check }: { items: readonly string[]; dark?: boolean; icon?: typeof Check }) { return <ul className="mt-7 grid gap-3 sm:grid-cols-2">{items.map((item) => <li key={item} className={`flex items-start gap-3 rounded-xl border p-4 text-sm leading-6 ${dark ? "border-white/10 bg-white/[0.035] text-white/75" : "border-slate-200 bg-white text-slate-700"}`}><Icon aria-hidden="true" className={`mt-1 size-4 shrink-0 ${dark ? "text-[var(--realm-gold-soft)]" : "text-[#9a7021]"}`} />{item}</li>)}</ul>; }
function PriceCard({ label, value, detail }: { label: string; value: string; detail: string }) { return <article className="rounded-2xl border border-slate-200 bg-white p-6"><p className="text-sm font-semibold text-[#8b641c]">{label}</p><p className="mt-3 text-3xl font-semibold text-[#071327]">{value}</p><p className="mt-2 text-sm leading-6 text-slate-600">{detail}</p></article>; }
