import Link from "next/link";

import { AdminShell } from "@/components/admin/AdminShell";
import { CheckpointQuestionAdminForm, RecordingAdminActions } from "@/components/admin/RecordingAdminActions";
import { AdminPanel, DataItem, StatusBadge, formatDate } from "@/components/admin/LmsUi";
import { requireAdmin } from "@/lib/adminAuth";
import { requireLmsAdminClient } from "@/lib/lms/adminData";
import { fetchAdminRecordingDetail } from "@/lib/lms/recordingData";

function object(value: unknown): Record<string, unknown> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function relation(value: unknown) { return Array.isArray(value) ? object(value[0]) : object(value); }

export default async function AdminRecordingDetailPage({ params }: { params: Promise<{ id: string }> }) {
  await requireAdmin(); const { id } = await params; const detail = await fetchAdminRecordingDetail(requireLmsAdminClient(), id);
  const progress = relation(detail.assignment.recording_progress); const statuses = (detail.assignment.recording_requirement_statuses ?? []) as Array<Record<string, unknown>>; const playback = (detail.assignment.recording_playback_sessions ?? []) as Array<Record<string, unknown>>;
  return <AdminShell title={detail.summary.recording.title} description={`${detail.summary.student.name} · ${detail.summary.course.code} · ${detail.summary.purposeLabel}`}>
    <div className="mb-5"><Link href="/admin/recordings" className="font-semibold text-amber-800">Back to recorded learning</Link></div>
    <div className="grid gap-6 lg:grid-cols-2"><AdminPanel title="Assignment"><dl className="grid gap-4 sm:grid-cols-2"><DataItem label="Student">{detail.summary.student.name} · {detail.summary.student.number}</DataItem><DataItem label="Course">{detail.summary.course.code} · {detail.summary.course.title}</DataItem><DataItem label="Session">{detail.summary.session.title}</DataItem><DataItem label="Recording">{detail.summary.recording.title}</DataItem><DataItem label="Purpose"><StatusBadge value={detail.summary.purposeLabel} /></DataItem><DataItem label="Assigned delivery route"><StatusBadge value={detail.summary.assignedDeliveryRoute} /></DataItem><DataItem label="Deadline">{formatDate(detail.summary.dueAt, true)}</DataItem><DataItem label="Progress"><StatusBadge value={String(progress.progress_status)} /></DataItem><DataItem label="Verified watch">{String(progress.watch_percentage ?? 0)}% of {String(detail.summary.effectiveRequirements.minWatchPercentage ?? 85)}% required</DataItem><DataItem label="Unique watched seconds">{String(progress.unique_watched_seconds ?? 0)}</DataItem><DataItem label="Integrity"><StatusBadge value={String(progress.integrity_status)} /></DataItem></dl></AdminPanel><AdminPanel title="Separate official records"><dl className="grid gap-4 sm:grid-cols-2"><DataItem label="Attendance"><StatusBadge value={String(detail.attendance?.attendance_status ?? "pending")} /></DataItem><DataItem label="Learning completion"><StatusBadge value={detail.summary.completionStatus ?? "not_started"} /></DataItem></dl><p className="mt-4 text-sm leading-6 text-slate-600">A recording assignment never replaces either record. Qualifying RP or DR-E completion updates the same attendance row only after all trusted requirements pass.</p></AdminPanel></div>
    <AdminPanel title="Requirement evidence"><div className="grid gap-3 md:grid-cols-2">{statuses.map((item) => <article key={String(item.id)} className="rounded-xl border border-slate-200 p-4"><strong>{String(item.requirement_type)}</strong><StatusBadge value={String(item.requirement_status)} /><p className="mt-2 text-xs text-slate-500">{String(item.evidence_source ?? "No evidence yet")}</p></article>)}</div></AdminPanel>
    <AdminPanel title="Checkpoint question builder"><CheckpointQuestionAdminForm checkpoints={detail.checkpoints.map((item) => ({ id: item.id, title: item.title }))} /></AdminPanel>
    <AdminPanel title="Playback evidence"><dl className="mb-5 grid gap-4 sm:grid-cols-3"><DataItem label="First access">{formatDate(typeof progress.first_access_at === "string" ? progress.first_access_at : null, true)}</DataItem><DataItem label="Last access">{formatDate(typeof progress.last_access_at === "string" ? progress.last_access_at : null, true)}</DataItem><DataItem label="Playback sessions">{playback.length}</DataItem></dl><p className="text-sm text-slate-600">Raw segments are retained as technical evidence and merged server-side; overlapping time is counted once.</p>{playback.length ? <ol className="mt-4 space-y-2">{playback.map((item) => <li key={String(item.id)} className="rounded-xl border border-slate-200 p-3 text-sm"><strong>{String(item.player_provider ?? "Provider")}</strong><span className="ml-2 text-slate-500">{formatDate(typeof item.started_at === "string" ? item.started_at : null, true)} · {String(item.playback_status)}</span></li>)}</ol> : null}</AdminPanel>
    <AdminPanel title="Administrative actions"><RecordingAdminActions assignmentId={id} /></AdminPanel>
    <AdminPanel title="Learning completion history">{detail.events.length ? <ol className="space-y-3">{detail.events.map((event) => <li key={event.id} className="rounded-xl border border-slate-200 p-4"><strong>{String(event.change_type)}</strong><p className="mt-1 text-sm text-slate-600">{String(event.reason)}</p><span className="mt-2 block text-xs text-slate-500">{formatDate(event.created_at, true)}</span></li>)}</ol> : <p className="text-sm text-slate-600">No learning-completion transition has been recorded.</p>}</AdminPanel>
    <AdminPanel title="Material audit history">{detail.audits.length ? <ol className="space-y-3">{detail.audits.map((event) => <li key={event.id} className="rounded-xl border border-slate-200 p-4"><strong>{String(event.action).replaceAll("_", " ")}</strong><span className="mt-2 block text-xs text-slate-500">{formatDate(event.created_at, true)}</span></li>)}</ol> : <p className="text-sm text-slate-600">No material recorded-learning audit event has been recorded.</p>}</AdminPanel>
  </AdminShell>;
}
