import Link from "next/link";
import { notFound } from "next/navigation";

import { LearningBreadcrumbs, SessionRecordings, SessionResources, SummaryReader, sessionStateLabel } from "@/components/student/StudentLearningUi";
import { DataCard, formatStudentDate, formatStudentTime, humanizeStudentValue, StudentPanel } from "@/components/student/StudentUi";
import { getStudentSessionDetail } from "@/lib/lms/studentLearning";
import { attendanceStatusLabels, deliveryRouteLabels } from "@/lib/lms/attendance";
import { getStudentSessionAttendance } from "@/lib/lms/studentAttendance";
import { requireRole } from "@/lib/lms/auth";
import { getStudentRecordingAssignments } from "@/lib/lms/recordingData";
import { fetchStudentAssignments, fetchStudentQuizzes } from "@/lib/lms/assessmentData";
import { requireLmsAdminClient } from "@/lib/lms/adminData";
import { getStudentAbsenceRequests } from "@/lib/lms/absenceData";
import { humanizeAbsenceValue } from "@/lib/lms/absence";

export default async function StudentSessionPage({ params }: { params: Promise<{ sessionId: string }> }) {
  const { sessionId } = await params;
  const { user } = await requireRole("student");
  const detail = await getStudentSessionDetail(sessionId);
  if (!detail) notFound();
  const { course, session } = detail;
  const assessmentClient = requireLmsAdminClient();
  const [attendance, recordingAssignments, allAssignments, allQuizzes, requirementLink, absenceRequests] = await Promise.all([getStudentSessionAttendance(sessionId, course.courseEnrollmentId), getStudentRecordingAssignments(user.id), fetchStudentAssignments(assessmentClient, user.id), fetchStudentQuizzes(assessmentClient, user.id), assessmentClient.from("session_recording_requirements").select("quiz_id, practical_assignment_id, reflection_assignment_id").eq("class_session_id", sessionId).maybeSingle(), getStudentAbsenceRequests(user.id)]);
  const absenceRequest = absenceRequests.find((item) => item.sessionId === sessionId);
  const recordedLearning = recordingAssignments.filter((item) => item.session.id === sessionId);
  const assignments = allAssignments.filter((item) => item.class_session_id === sessionId);
  const quizzes = allQuizzes.filter((item) => item.class_session_id === sessionId);
  return <div className="space-y-6"><div><LearningBreadcrumbs items={[{ href: "/student/courses", label: "My Courses" }, { href: `/student/courses/${course.courseEnrollmentId}`, label: course.code }, { label: session.title }]} /><header className="rounded-3xl bg-[linear-gradient(135deg,#092648,#0e3a68)] p-6 text-white shadow-lg md:p-8"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[var(--realm-gold-soft)]">{course.code} · {course.title}</p>{session.sessionNumber ? <p className="mt-4 text-sm font-semibold text-white/70">Session {session.sessionNumber}</p> : null}<h1 className="mt-2 max-w-4xl text-3xl font-semibold tracking-tight md:text-4xl">{session.title}</h1>{session.description ? <p className="mt-4 max-w-3xl leading-7 text-white/75">{session.description}</p> : null}<dl className="mt-6 grid gap-4 border-t border-white/15 pt-5 sm:grid-cols-2 lg:grid-cols-4"><HeaderItem label="Date" value={formatStudentDate(session.scheduledStartAt)} /><HeaderItem label="Time" value={formatStudentTime(session.scheduledStartAt)} /><HeaderItem label="Delivery" value={humanizeStudentValue(session.deliveryMode)} /><HeaderItem label="Status" value={sessionStateLabel(session)} /><HeaderItem label="Session Type" value={humanizeStudentValue(session.sessionType)} /><HeaderItem label="Facilitator" value={session.facilitator ?? "To be announced"} /></dl></header></div>

    {session.status === "cancelled" ? <div role="status" className="rounded-2xl border border-rose-200 bg-rose-50 p-5 text-rose-900"><h2 className="font-semibold">This class session has been cancelled.</h2><p className="mt-1 text-sm leading-6">Please use the current student schedule for any replacement session information.</p></div> : null}
    {session.status === "rescheduled" ? <div role="status" className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-amber-900"><h2 className="font-semibold">This class session has been rescheduled.</h2><p className="mt-1 text-sm leading-6">The date and time shown above are the current published schedule.</p></div> : null}

    <div className="grid gap-6 xl:grid-cols-2"><StudentPanel title="Class Access"><div className="grid gap-3 sm:grid-cols-2"><DataCard label="Delivery Mode" value={humanizeStudentValue(session.deliveryMode)} /><DataCard label="Timezone" value={session.timezone} />{(session.deliveryMode === "physical" || session.deliveryMode === "hybrid") && session.physicalLocation ? <DataCard label="Physical Location" value={session.physicalLocation} /> : null}</div>{session.deliveryMode === "online" || session.deliveryMode === "hybrid" ? <div className="mt-5 border-t border-slate-200 pt-5"><h3 className="font-semibold text-[#071327]">Live Class</h3>{detail.liveAccess.state === "available" && detail.liveAccess.href ? <a href={detail.liveAccess.href} target="_blank" rel="noreferrer noopener" className="mt-3 inline-flex min-h-11 items-center rounded-xl bg-[#0b315c] px-5 py-2 text-sm font-semibold text-white hover:bg-[#124574] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-amber-700">Join Live Class<span className="sr-only"> (opens in a new tab)</span></a> : <p className="mt-2 text-sm leading-6 text-slate-600">{detail.liveAccess.message}</p>}</div> : null}</StudentPanel><StudentPanel title="Session Details"><div className="grid gap-3 sm:grid-cols-2"><DataCard label="Course" value={`${course.code} · ${course.title}`} /><DataCard label="Programme Component" value={course.componentLabel} /><DataCard label="Session Type" value={humanizeStudentValue(session.sessionType)} /><DataCard label="Teaching Event" value={sessionStateLabel(session)} detail="This does not indicate individual learning completion." /></div></StudentPanel></div>

    <div className="grid gap-6 xl:grid-cols-2"><StudentPanel title="My Attendance">{attendance.attendance ? <div className="grid gap-3 sm:grid-cols-2"><DataCard label="Assigned Route" value={deliveryRouteLabels[attendance.attendance.assigned_delivery_route as keyof typeof deliveryRouteLabels]} /><DataCard label="Attendance Status" value={attendanceStatusLabels[attendance.attendance.attendance_status as keyof typeof attendanceStatusLabels]} detail={attendance.attendance.finalized_at ? `Finalized ${formatStudentDate(attendance.attendance.finalized_at, true)}` : "Pending staff finalization"} /></div> : <p className="text-sm leading-6 text-slate-600">Attendance has not yet been recorded for this session.</p>}</StudentPanel><StudentPanel title="Learning Completion">{attendance.completion ? <DataCard label="Completion Status" value={humanizeStudentValue(attendance.completion.completion_status)} detail={attendance.completion.verified_at ? formatStudentDate(attendance.completion.verified_at, true) : "Not yet verified"} /> : <p className="text-sm leading-6 text-slate-600">Learning completion has not yet been initialized.</p>}</StudentPanel></div>

    {session.status !== "cancelled" && absenceRequest ? <StudentPanel title="Absence & Make-Up"><p className="text-sm text-slate-700">Absence request: <strong>{humanizeAbsenceValue(absenceRequest.status)}</strong>{absenceRequest.makeup ? ` · Make-Up: ${humanizeAbsenceValue(absenceRequest.makeup.status)}` : ""}</p><Link href={`/student/absences/${absenceRequest.id}`} className="mt-4 inline-flex rounded-xl bg-[#0b315c] px-4 py-2 font-semibold text-white">{absenceRequest.makeup && !["completed", "late_complete"].includes(absenceRequest.makeup.status) ? "Continue Make-Up" : absenceRequest.makeup ? "View Make-Up Completed" : "View Absence Request"}</Link></StudentPanel> : session.status !== "cancelled" && !attendance.attendance?.attendance_status?.match(/^(present|late|partial|verified_recorded_attendance)$/) ? <StudentPanel title="Need to report an absence?"><p className="text-sm leading-6 text-slate-700">Use the protected absence workflow for this required class session.</p><Link href="/student/absences/new" className="mt-4 inline-flex rounded-xl bg-[#0b315c] px-4 py-2 font-semibold text-white">Report Absence</Link></StudentPanel> : null}

    <StudentPanel title="Class Summary" className="scroll-mt-8"><SummaryReader summary={detail.summary} /></StudentPanel>
    <StudentPanel title="Learning Resources" className="scroll-mt-8"><div id="resources" className="scroll-mt-8"><SessionResources resources={detail.resources} /></div></StudentPanel>
    <StudentPanel title="Class Recording" className="scroll-mt-8"><SessionRecordings recordings={detail.recordings} /></StudentPanel>
    {assignments.length || quizzes.length ? <StudentPanel title="Session assessments"><div className="grid gap-3 md:grid-cols-2">{assignments.map((item) => <Link key={item.id} href={`/student/assignments/${item.id}`} className="rounded-xl border border-slate-200 p-4"><strong>{item.title}</strong><p className="mt-1 text-sm text-slate-600">Submit {humanizeStudentValue(item.assignment_type)}</p></Link>)}{quizzes.map((item) => <Link key={item.id} href={`/student/quizzes/${item.id}`} className="rounded-xl border border-slate-200 p-4"><strong>{item.title}</strong><p className="mt-1 text-sm text-slate-600">Complete quiz</p></Link>)}</div></StudentPanel> : null}
    {recordedLearning.length ? <StudentPanel title="My recorded-learning requirements" description="Only assessments explicitly linked by REALMS are verification requirements. Viewing progress and learning completion remain separate from the official attendance row."><div className="grid gap-3 lg:grid-cols-2">{recordedLearning.map((item) => <article key={item.id} className="rounded-xl border border-slate-200 p-4"><Link href={`/student/recordings/${item.id}`} className="block hover:text-amber-800"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-amber-700">{item.purposeLabel}</p><h3 className="mt-2 font-semibold text-[#071327]">{item.recording.title}</h3></Link><dl className="mt-4 grid gap-2 text-sm text-slate-600 sm:grid-cols-2"><div><dt className="font-semibold text-slate-800">Watch</dt><dd>{Math.floor(item.progress.watchPercentage)}% of required {Number(item.effectiveRequirements.minWatchPercentage ?? 85)}%</dd></div><div><dt className="font-semibold text-slate-800">Checkpoints</dt><dd>{humanizeStudentValue(item.requirementSummary.checkpoints)} · {Number(item.effectiveRequirements.requiredCheckpointCount ?? 2)} required</dd></div><div><dt className="font-semibold text-slate-800">Quiz</dt><dd>{humanizeStudentValue(item.requirementSummary.quiz)}{requirementLink.data?.quiz_id ? <Link href={`/student/quizzes/${requirementLink.data.quiz_id}`} className="ml-2 font-semibold text-amber-800">Complete quiz</Link> : null}</dd></div><div><dt className="font-semibold text-slate-800">Practical / reflection</dt><dd>{humanizeStudentValue(item.requirementSummary.practical !== "not_required" ? item.requirementSummary.practical : item.requirementSummary.reflection)}{item.requirementSummary.practical !== "not_required" && requirementLink.data?.practical_assignment_id ? <Link href={`/student/assignments/${requirementLink.data.practical_assignment_id}`} className="ml-2 font-semibold text-amber-800">Submit practical</Link> : item.requirementSummary.reflection !== "not_required" && requirementLink.data?.reflection_assignment_id ? <Link href={`/student/assignments/${requirementLink.data.reflection_assignment_id}`} className="ml-2 font-semibold text-amber-800">Submit reflection</Link> : null}</dd></div><div><dt className="font-semibold text-slate-800">Deadline</dt><dd>{item.dueAt ? formatStudentDate(item.dueAt, true) : "No academic deadline"}</dd></div><div><dt className="font-semibold text-slate-800">Status</dt><dd>{humanizeStudentValue(item.displayStatus)}</dd></div></dl></article>)}</div></StudentPanel> : null}

    <nav aria-label="Class session navigation" className="grid gap-4 sm:grid-cols-2">{detail.previousSession ? <Link href={`/student/sessions/${detail.previousSession.id}`} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-amber-700"><span className="text-xs font-semibold uppercase tracking-[0.12em] text-amber-700">Previous Session</span><span className="mt-2 block font-semibold text-[#071327]">{detail.previousSession.title}</span></Link> : <div />}{detail.nextSession ? <Link href={`/student/sessions/${detail.nextSession.id}`} className="rounded-2xl border border-slate-200 bg-white p-5 text-right shadow-sm focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-amber-700"><span className="text-xs font-semibold uppercase tracking-[0.12em] text-amber-700">Next Session</span><span className="mt-2 block font-semibold text-[#071327]">{detail.nextSession.title}</span></Link> : null}</nav>
    <Link href={`/student/courses/${course.courseEnrollmentId}`} className="inline-flex min-h-11 items-center rounded-xl border border-slate-300 bg-white px-5 py-2 text-sm font-semibold text-[#0b315c] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-amber-700">Back to {course.code}</Link>
  </div>;
}

function HeaderItem({ label, value }: { label: string; value: string }) {
  return <div><dt className="text-xs font-semibold uppercase tracking-[0.12em] text-white/60">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>;
}
