import { NextResponse } from "next/server";
import { isAdminAuthenticated } from "@/lib/adminAuth";
import { cohortStatuses, isOneOf, isUuid, readNullableDate, readNullableTimestamp, readText } from "@/lib/lms/adminConstants";
import { recordLmsAudit } from "@/lib/lms/adminAudit";
import { fetchAdminCohort, requireLmsAdminClient } from "@/lib/lms/adminData";
import { cohortCalendarValidationErrors } from "@/lib/lms/cohortCalendar";

export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) { if (!(await isAdminAuthenticated())) return NextResponse.json({ message: "Unauthorized." }, { status: 401 }); const { id } = await params; if (!isUuid(id)) return NextResponse.json({ message: "Cohort not found." }, { status: 404 }); try { return NextResponse.json(await fetchAdminCohort(requireLmsAdminClient(), id)); } catch { return NextResponse.json({ message: "Cohort could not be loaded." }, { status: 500 }); } }
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {
  if (!(await isAdminAuthenticated())) return NextResponse.json({ message: "Unauthorized." }, { status: 401 }); const { id } = await params; if (!isUuid(id)) return NextResponse.json({ message: "Cohort not found." }, { status: 404 });
  const body = await request.json().catch(() => null) as Record<string, unknown> | null; if (!body || !isOneOf(cohortStatuses, body.status)) return NextResponse.json({ message: "A valid cohort status is required." }, { status: 400 });
  const name = readText(body.name, 180); const academicYear = readText(body.academic_year, 20); const capacity = body.maximum_capacity === "" || body.maximum_capacity == null ? null : Number(body.maximum_capacity); if (!name || (capacity !== null && (!Number.isInteger(capacity) || capacity < 1 || capacity > 100000))) return NextResponse.json({ message: "A valid cohort name and capacity are required." }, { status: 400 });
  const dateFields = ["start_date", "end_date", "teaching_start_date", "teaching_end_date", "completion_period_start_date", "completion_period_end_date", "application_open_date", "application_close_date", "orientation_date", "matriculation_date", "graduation_date"] as const; const timestampFields = ["orientation_start_at", "matriculation_start_at", "graduation_start_at"] as const; const updates: Record<string, unknown> = { name, status: body.status, academic_year: academicYear, maximum_capacity: capacity, description: readText(body.description), internal_notes: readText(body.internal_notes), updated_at: new Date().toISOString() };
  for (const field of dateFields) { const date = readNullableDate(body[field]); if (date === undefined) return NextResponse.json({ message: `A valid ${field.replaceAll("_", " ")} is required.` }, { status: 400 }); updates[field] = date; }
  for (const field of timestampFields) { const timestamp = readNullableTimestamp(body[field]); if (timestamp === undefined) return NextResponse.json({ message: `A valid ${field.replaceAll("_", " ")} is required.` }, { status: 400 }); updates[field] = timestamp; }
  const teachingWeekCount = body.teaching_week_count === "" || body.teaching_week_count == null ? null : Number(body.teaching_week_count); updates.teaching_week_count = teachingWeekCount;
  const calendarErrors = cohortCalendarValidationErrors({ startDate: updates.start_date as string | null, endDate: updates.end_date as string | null, teachingStartDate: updates.teaching_start_date as string | null, teachingEndDate: updates.teaching_end_date as string | null, teachingWeekCount, completionPeriodStartDate: updates.completion_period_start_date as string | null, completionPeriodEndDate: updates.completion_period_end_date as string | null, orientationDate: updates.orientation_date as string | null, orientationStartAt: updates.orientation_start_at as string | null, matriculationDate: updates.matriculation_date as string | null, matriculationStartAt: updates.matriculation_start_at as string | null, graduationDate: updates.graduation_date as string | null, graduationStartAt: updates.graduation_start_at as string | null });
  if (calendarErrors.length) return NextResponse.json({ message: calendarErrors[0], errors: calendarErrors }, { status: 400 });
  const supabase = requireLmsAdminClient(); const current = await supabase.from("cohorts").select("*").eq("id", id).maybeSingle(); if (current.error || !current.data) return NextResponse.json({ message: "Cohort not found." }, { status: 404 }); const result = await supabase.from("cohorts").update(updates).eq("id", id).select("*").single(); if (result.error) return NextResponse.json({ message: "Cohort could not be updated." }, { status: 500 }); await recordLmsAudit(supabase, { action: "cohort_updated", entityType: "cohort", entityId: id, metadata: { previous: current.data, next: result.data } }); return NextResponse.json({ cohort: result.data });
}
