import Link from "next/link";
import { notFound } from "next/navigation";

import { AdminShell } from "@/components/admin/AdminShell";
import { EvaluateEngagementButton, MentorAssignmentForm, NoticeForm, NoticeWorkflowButtons, RecoveryPlanForm, RecoveryPlanStatusForm, ReviewCaseForm, ReviewCaseUpdateForm, StandingChangeForm } from "@/components/admin/EngagementActions";
import { AdminPanel, DataItem, StatusBadge, formatDate } from "@/components/admin/LmsUi";
import { requireAdmin } from "@/lib/adminAuth";
import { isUuid } from "@/lib/lms/adminConstants";
import { requireLmsAdminClient } from "@/lib/lms/adminData";
import { humanizeEngagement } from "@/lib/lms/engagement";
import { fetchAtRiskStudentDetail } from "@/lib/lms/engagementData";

export const dynamic = "force-dynamic";
function row(value: unknown) { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function mentorProfile(value: Record<string, unknown>) { return row(Array.isArray(value.profiles) ? value.profiles[0] : value.profiles); }

export default async function AtRiskStudentPage({ params }: { params: Promise<{ studentEnrollmentId: string }> }) {
  await requireAdmin(); const { studentEnrollmentId } = await params; if (!isUuid(studentEnrollmentId)) notFound();
  const data = await fetchAtRiskStudentDetail(requireLmsAdminClient(), studentEnrollmentId); const activeMentor = data.mentorAssignments.find((item) => item.assignment_status === "active"); const mentor = activeMentor ? mentorProfile(activeMentor) : {};
  const noticeOptions = data.notices.map((item) => ({ id: String(item.id), label: `${humanizeEngagement(String(item.notice_type))} · ${String(item.title)}` })); const caseOptions = data.reviewCases.map((item) => ({ id: String(item.id), label: `${humanizeEngagement(String(item.review_type))} · ${String(item.case_title)}` }));
  return <AdminShell title={`Student Engagement · ${String(data.student.preferred_name || data.student.legal_name)}`} description={`${String(data.student.student_number)} · ${String(data.cohort.code)} · Verified facts and protected, human-led support decisions`}>
    <div className="mb-6 flex flex-wrap items-start justify-between gap-4"><Link href="/admin/at-risk" className="font-semibold text-amber-800">← Student Engagement</Link><EvaluateEngagementButton studentEnrollmentId={studentEnrollmentId} /></div>
    <AdminPanel title="Student Overview"><dl className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><DataItem label="Student">{String(data.student.legal_name)}</DataItem><DataItem label="Cohort">{String(data.cohort.name)}</DataItem><DataItem label="Discipleship Route">{humanizeEngagement(String(data.studentEnrollment.discipleship_route))}</DataItem><DataItem label="Skill Pathway">{humanizeEngagement(String(data.studentEnrollment.skill_pathway))}</DataItem><DataItem label="Academic Standing"><StatusBadge value={String(data.studentEnrollment.academic_standing)} /></DataItem><DataItem label="Standing Review">{data.studentEnrollment.standing_review_required ? "Required" : "Not currently flagged"}</DataItem><DataItem label="Assigned Mentor">{String(mentor.preferred_name || mentor.full_name || "Not assigned")}</DataItem><DataItem label="Last Evaluated">{formatDate(String(data.studentEnrollment.last_engagement_evaluated_at ?? ""), true)}</DataItem></dl></AdminPanel>
    <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(data.metrics).filter(([key]) => key !== "lastMeaningfulActivityAt").map(([key, value]) => <div key={key} className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-xs uppercase tracking-wide text-slate-500">{humanizeEngagement(key.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`))}</p><p className="mt-2 text-xl font-semibold">{value ?? "Not established"}</p></div>)}</div>
    <p className="mt-3 text-sm text-slate-600">Last meaningful activity: {data.metrics.lastMeaningfulActivityAt ? formatDate(data.metrics.lastMeaningfulActivityAt, true) : "No meaningful activity has been recorded yet. No inactivity threshold is assumed."}</p>
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><AdminPanel title="Open Engagement Alerts" description="Operational facts only; a review alert is not a misconduct finding."><div className="space-y-3">{data.alerts.map((alert) => <article key={alert.id} className="rounded-xl border border-slate-200 p-4"><div className="flex justify-between gap-3"><strong>{String(alert.alert_title)}</strong><StatusBadge value={String(alert.severity)} /></div><p className="mt-2 text-sm text-slate-600">{String(alert.alert_summary)}</p><p className="mt-2 text-xs text-slate-500">{humanizeEngagement(String(alert.alert_status))} · last detected {formatDate(String(alert.last_detected_at), true)}</p></article>)}{!data.alerts.length ? <p className="text-sm text-slate-600">No engagement alerts have been generated.</p> : null}</div></AdminPanel><AdminPanel title="Assign Mentor" description="Only profiles with an active mentor role can be assigned. Changing mentors ends the prior primary assignment with a reason."><MentorAssignmentForm studentEnrollmentId={studentEnrollmentId} mentors={data.mentorOptions.map((item) => ({ id: item.id, label: String(item.preferred_name || item.full_name) }))} /></AdminPanel></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><AdminPanel title="Create Formal Notice" description="Drafts remain hidden from students until an administrator intentionally issues them."><NoticeForm studentEnrollmentId={studentEnrollmentId} alerts={data.alerts.filter((item) => item.alert_status !== "resolved").map((item) => ({ id: String(item.id), label: String(item.alert_title) }))} /></AdminPanel><AdminPanel title="Warnings and Notices"><div className="space-y-3">{data.notices.map((notice) => <article key={notice.id} className="rounded-xl border border-slate-200 p-4"><div className="flex justify-between gap-3"><strong>{String(notice.title)}</strong><StatusBadge value={String(notice.notice_status)} /></div><p className="mt-2 text-sm text-slate-600">{String(notice.reason_summary)}</p>{notice.student_response ? <p className="mt-3 rounded-lg bg-slate-50 p-3 text-sm"><strong>Student response:</strong> {String(notice.student_response)}</p> : null}<NoticeWorkflowButtons noticeId={String(notice.id)} status={String(notice.notice_status)} /></article>)}{!data.notices.length ? <p className="text-sm text-slate-600">No formal notices have been created.</p> : null}</div></AdminPanel></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><AdminPanel title="Academic Standing Change" description="Standing changes require a reason and supporting notice or review case where relevant. They never occur from alert evaluation alone."><StandingChangeForm studentEnrollmentId={studentEnrollmentId} current={String(data.studentEnrollment.academic_standing)} notices={noticeOptions} cases={caseOptions} /></AdminPanel><AdminPanel title="Standing History"><ol className="space-y-3">{data.standingHistory.map((event) => <li key={event.id} className="border-l-2 border-amber-300 pl-4 text-sm"><strong>{humanizeEngagement(String(event.previous_standing))} → {humanizeEngagement(String(event.new_standing))}</strong><p className="mt-1 text-slate-600">{String(event.reason)}</p><time className="text-xs text-slate-500">{formatDate(String(event.created_at), true)}</time></li>)}{!data.standingHistory.length ? <li className="text-sm text-slate-600">No standing changes have been recorded.</li> : null}</ol></AdminPanel></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><AdminPanel title="Create Recovery Plan" description="Use concrete, verifiable actions. Plans do not close automatically when a date passes."><RecoveryPlanForm studentEnrollmentId={studentEnrollmentId} mentorAssignmentId={activeMentor ? String(activeMentor.id) : undefined} noticeOptions={noticeOptions} /></AdminPanel><AdminPanel title="Recovery Plans and Actions"><div className="space-y-4">{data.recoveryPlans.map((plan) => <article key={plan.id} className="rounded-xl border border-slate-200 p-4"><div className="flex justify-between gap-3"><strong>{String(plan.plan_title)}</strong><StatusBadge value={String(plan.plan_status)} /></div><p className="mt-2 text-sm text-slate-600">{String(plan.reason_summary)}</p><ul className="mt-3 space-y-2 text-sm">{data.recoveryActions.filter((action) => action.recovery_plan_id === plan.id).map((action) => <li key={action.id}>• {String(action.title)} · {humanizeEngagement(String(action.action_status))}</li>)}</ul><RecoveryPlanStatusForm planId={String(plan.id)} current={String(plan.plan_status)} /></article>)}{!data.recoveryPlans.length ? <p className="text-sm text-slate-600">No recovery plans have been created.</p> : null}</div></AdminPanel></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><AdminPanel title="Open Review Case" description="The student receives the concern in substance and a response opportunity. Recommendations do not change enrolment status."><ReviewCaseForm studentEnrollmentId={studentEnrollmentId} /></AdminPanel><AdminPanel title="Participation and Status Reviews"><div className="space-y-4">{data.reviewCases.map((review) => <article key={review.id} className="rounded-xl border border-slate-200 p-4"><div className="flex justify-between gap-3"><strong>{String(review.case_title)}</strong><StatusBadge value={String(review.case_status)} /></div><p className="mt-2 text-sm text-slate-600">{String(review.concern_summary)}</p>{review.student_response ? <p className="mt-3 rounded-lg bg-slate-50 p-3 text-sm"><strong>Student response:</strong> {String(review.student_response)}</p> : null}<ReviewCaseUpdateForm caseId={String(review.id)} currentStatus={String(review.case_status)} /></article>)}{!data.reviewCases.length ? <p className="text-sm text-slate-600">No review cases have been opened.</p> : null}</div></AdminPanel></div>
    <AdminPanel title="Mentor Follow-Ups" description="Minimal operational follow-up only; no counselling transcript or private evidence." ><div className="space-y-3">{data.followups.map((item) => <article key={item.id} className="rounded-xl border border-slate-200 p-4 text-sm"><strong>{humanizeEngagement(String(item.contact_status))} · {humanizeEngagement(String(item.contact_method))}</strong><p className="mt-2 text-slate-600">{String(item.contact_summary ?? "No summary recorded")}</p><time className="text-xs text-slate-500">{formatDate(String(item.contacted_at), true)}</time></article>)}{!data.followups.length ? <p className="text-sm text-slate-600">No mentor follow-ups have been recorded.</p> : null}</div></AdminPanel>
  </AdminShell>;
}
