"use client";

import Link from "next/link";
import { useState } from "react";
import { assessmentCategories, assessmentDomains, assignmentTypes, humanizeAssessment } from "@/lib/lms/assessment";

type Row = Record<string, unknown>;
function object(value: unknown): Row { return value && typeof value === "object" && !Array.isArray(value) ? value as Row : {}; }
function relation(value: unknown) { return Array.isArray(value) ? object(value[0]) : object(value); }
function date(value: unknown) { return typeof value === "string" && value ? new Intl.DateTimeFormat("en-NG", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "No deadline"; }

export function AssignmentManager({ assignments, options, scope = "admin" }: { assignments: Row[]; options: { offerings: Row[]; sessions: Row[] }; scope?: "admin" | "facilitator" }) {
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const base = `/api/${scope}/assignments`; const pageBase = `/${scope}/assignments`;
  async function create(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const form = new FormData(event.currentTarget); const body = Object.fromEntries(form) as Row; body.allow_late_submission = form.get("allow_late_submission") === "on"; body.text_response_required = form.get("text_response_required") === "on"; body.repository_url_required = form.get("repository_url_required") === "on"; body.deployment_url_required = form.get("deployment_url_required") === "on"; body.external_url_allowed = form.get("external_url_allowed") === "on"; body.file_upload_allowed = form.get("file_upload_allowed") === "on"; body.domain_override_confirmed = form.get("domain_override_confirmed") === "on"; const response = await fetch(base, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json(); setBusy(false); if (!response.ok) return setMessage(payload.message || "Assignment draft could not be created."); window.location.href = `${pageBase}/${payload.assignment.id}`; }
  return <div className="space-y-6">{message ? <p role="status" className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950">{message}</p> : null}
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold text-[#071327]">Create assignment draft</h2><p className="mt-1 text-sm text-slate-600">Assessment type controls presentation; domain and category preserve the academic meaning used by later programme scoring.</p><form onSubmit={create} className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">
      <Label title="Cohort course"><select name="cohort_course_id" required className="field"><option value="">Choose course</option>{options.offerings.map((raw) => { const offering = object(raw); const course = relation(offering.courses); const cohort = relation(offering.cohorts); return <option key={String(offering.id)} value={String(offering.id)}>{String(cohort.code)} · {String(course.code)} · {String(course.title)}</option>; })}</select></Label>
      <Label title="Optional class session"><select name="class_session_id" className="field"><option value="">Not linked to one session</option>{options.sessions.map((raw) => <option key={String(raw.id)} value={String(raw.id)}>{String(raw.title)}</option>)}</select></Label>
      <Label title="Title"><input name="title" required className="field" /></Label>
      <Label title="Assignment type"><select name="assignment_type" className="field">{assignmentTypes.map((value) => <option key={value} value={value}>{humanizeAssessment(value)}</option>)}</select></Label>
      <Label title="Assessment domain"><select name="assessment_domain" className="field">{assessmentDomains.map((value) => <option key={value} value={value}>{humanizeAssessment(value)}</option>)}</select></Label>
      <Label title="Assessment category"><select name="assessment_category" className="field">{assessmentDomains.flatMap((domain) => assessmentCategories[domain].map((value) => <option key={value} value={value}>{humanizeAssessment(value)}</option>))}</select></Label>
      <Label title="Maximum score"><input name="max_score" type="number" min="0.01" step="0.01" defaultValue="100" required className="field" /></Label>
      <Label title="Due date"><input name="due_at" type="datetime-local" className="field" /></Label>
      <Label title="Maximum attempts"><input name="max_submission_attempts" type="number" min="1" defaultValue="1" required className="field" /></Label>
      <Label title="Description"><textarea name="description" rows={3} className="field" /></Label><Label title="Instructions"><textarea name="instructions" rows={3} className="field" /></Label>
      <fieldset className="rounded-xl border border-slate-200 p-3 text-sm"><legend className="px-1 font-semibold">Submission requirements</legend>{[["text_response_required", "Written response"], ["repository_url_required", "Repository URL"], ["deployment_url_required", "Deployment URL"], ["external_url_allowed", "External URL allowed"], ["file_upload_allowed", "Private file upload allowed"], ["allow_late_submission", "Late submission allowed"]].map(([name, label]) => <label key={name} className="mt-2 flex items-center gap-2"><input name={name} type="checkbox" defaultChecked={name === "external_url_allowed" || name === "allow_late_submission"} />{label}</label>)}</fieldset>
      <label className="flex items-start gap-2 text-sm md:col-span-2 xl:col-span-3"><input name="domain_override_confirmed" type="checkbox" className="mt-1" />I confirm any intentional mismatch between the course category and assessment domain.</label>
      <button disabled={busy} className="rounded-xl bg-[#071327] px-5 py-3 text-sm font-semibold text-white disabled:opacity-50 md:col-span-2 xl:col-span-3">Create draft</button>
    </form></section>
    {scope === "admin" ? <form method="get" className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-5 md:grid-cols-4 xl:grid-cols-7" aria-label="Assignment filters">
      <select name="cohort" className="field"><option value="">All cohorts</option>{[...new Map(options.offerings.map((raw) => { const cohort = relation(raw.cohorts); return [String(cohort.id), cohort]; })).values()].map((cohort) => <option key={String(cohort.id)} value={String(cohort.id)}>{String(cohort.code)}</option>)}</select>
      <select name="course" className="field"><option value="">All courses</option>{[...new Map(options.offerings.map((raw) => { const course = relation(raw.courses); return [String(course.id), course]; })).values()].map((course) => <option key={String(course.id)} value={String(course.id)}>{String(course.code)}</option>)}</select>
      <select name="type" className="field"><option value="">All types</option>{assignmentTypes.map((value) => <option key={value} value={value}>{humanizeAssessment(value)}</option>)}</select>
      <select name="domain" className="field"><option value="">All domains</option>{assessmentDomains.map((value) => <option key={value}>{humanizeAssessment(value)}</option>)}</select>
      <select name="category" className="field"><option value="">All categories</option>{assessmentDomains.flatMap((domain) => assessmentCategories[domain].map((value) => <option key={value}>{humanizeAssessment(value)}</option>))}</select>
      <select name="status" className="field"><option value="">All statuses</option>{["draft", "published", "closed", "archived"].map((value) => <option key={value}>{humanizeAssessment(value)}</option>)}</select>
      <select name="due" className="field"><option value="">Any due date</option><option value="future">Future / open</option><option value="overdue">Overdue</option></select>
      <button className="rounded-xl bg-[#071327] px-4 py-2 text-sm font-semibold text-white md:col-span-4 xl:col-span-7">Apply filters</button>
    </form> : null}
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 p-5"><h2 className="text-lg font-semibold text-[#071327]">Assignments</h2><p className="mt-1 text-sm text-slate-600">{assignments.length} record{assignments.length === 1 ? "" : "s"}. Use URL filters for cohort, course, type, domain, category, status, and due.</p></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{["Title", "Course / Cohort", "Type", "Domain / Category", "Due", "Status", "Content", "Submissions", "Awaiting review"].map((head) => <th key={head} className="px-4 py-3">{head}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{assignments.map((raw) => { const row = object(raw); const course = object(row.course); const cohort = object(row.cohort); return <tr key={String(row.id)}><td className="px-4 py-4"><Link href={`${pageBase}/${String(row.id)}`} className="font-semibold text-amber-800 hover:underline">{String(row.title)}</Link></td><td className="px-4 py-4">{String(course.code ?? "Course")}<br /><span className="text-slate-500">{String(cohort.code ?? "Cohort")}</span></td><td className="px-4 py-4">{humanizeAssessment(String(row.assignment_type))}</td><td className="px-4 py-4">{humanizeAssessment(String(row.assessment_domain))}<br /><span className="text-slate-500">{humanizeAssessment(String(row.assessment_category))}</span></td><td className="px-4 py-4">{date(row.due_at)}</td><td className="px-4 py-4">{humanizeAssessment(String(row.assignment_status))}</td><td className="px-4 py-4">{humanizeAssessment(String(row.content_readiness))}</td><td className="px-4 py-4">{String(row.submission_count ?? 0)}</td><td className="px-4 py-4">{String(row.awaiting_review_count ?? 0)}</td></tr>; })}</tbody></table></div></section>
  </div>;
}
function Label({ title, children }: { title: string; children: React.ReactNode }) { return <label className="text-sm font-medium text-slate-800">{title}{children}</label>; }
