"use client";

import { useRouter } from "next/navigation";
import { type FormEvent, type ReactNode, useState } from "react";

const field = "min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm";

function values(form: HTMLFormElement) { const payload: Record<string, unknown> = {}; for (const [key, value] of new FormData(form)) payload[key] = value; return payload; }

export function Build12ActionForm({ endpoint, button, children, method = "POST" }: { endpoint: string; button: string; children?: ReactNode; method?: "POST" | "PATCH" }) {
  const router = useRouter(); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); try { const response = await fetch(endpoint, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(values(event.currentTarget)) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message || "The action could not be completed."); setMessage(data.message || "Saved."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "The action could not be completed."); } finally { setBusy(false); } }
  return <form onSubmit={submit} className="space-y-3 rounded-2xl border border-slate-200 bg-white p-4">{children}{message ? <p role="status" className="text-sm text-amber-800">{message}</p> : null}<button disabled={busy} className="min-h-11 rounded-xl bg-[#071327] px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{busy ? "Working…" : button}</button></form>;
}

export function EligibilityCheckForm({ studentEnrollmentId }: { studentEnrollmentId: string }) { return <Build12ActionForm endpoint="/api/admin/graduation/check" button="Check Eligibility"><input type="hidden" name="student_enrollment_id" value={studentEnrollmentId} /><input name="actor_name" required placeholder="Named authorised reviewer" className={field} /></Build12ActionForm>; }

export function IdentityReconciliationForm({ confirmationId, student, enrollment }: { confirmationId: string; student: Record<string, unknown>; enrollment: Record<string, unknown> }) { return <Build12ActionForm endpoint={`/api/admin/graduation/${confirmationId}/identity`} button="Mark Identity Reconciled"><input type="hidden" name="legal_name" value={String(student.legal_name)} /><input type="hidden" name="student_number" value={String(student.student_number)} /><input type="hidden" name="cohort_id" value={String(enrollment.cohort_id)} /><input type="hidden" name="discipleship_route" value={String(enrollment.discipleship_route)} /><input type="hidden" name="skill_pathway" value={String(enrollment.skill_pathway)} /><input name="actor_name" required placeholder="Named identity reviewer" className={field} /><textarea name="reason" required minLength={10} placeholder="Reconciliation evidence and record checked" className={field} /></Build12ActionForm>; }

export function AcademicReconciliationForm({ confirmationId }: { confirmationId: string }) { return <Build12ActionForm endpoint={`/api/admin/graduation/${confirmationId}/academic`} button="Mark Academic Record Reconciled"><input name="actor_name" required placeholder="Named academic reviewer" className={field} /><textarea name="reason" required minLength={10} placeholder="Academic records, result batch and mandatory evidence checked" className={field} /></Build12ActionForm>; }

export function GraduationTransitionForm({ confirmationId, status }: { confirmationId: string; status: string }) {
  if (status === "eligible" || status === "reconciliation_required") return <Build12ActionForm endpoint={`/api/admin/graduation/${confirmationId}/transition`} button="Submit for Approval"><input type="hidden" name="action" value="submit" /><input name="actor_name" required placeholder="Named submitter" className={field} /><textarea name="reason" required placeholder="Submission note" className={field} /></Build12ActionForm>;
  if (status === "awaiting_approval") return <Build12ActionForm endpoint={`/api/admin/graduation/${confirmationId}/transition`} button="Approve Graduation"><input type="hidden" name="action" value="approve" /><input name="actor_name" required placeholder="Named authorised approver (different from submitter)" className={field} /><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Completion date<input name="completion_date" type="date" required className={field} /></label><label className="text-sm font-semibold">Graduation date, if applicable<input name="graduation_date" type="date" className={field} /></label></div><input name="decision_reference" required placeholder="Authorised decision reference" className={field} /><textarea name="decision_note" required minLength={10} placeholder="Authorised decision note" className={field} /></Build12ActionForm>;
  if (status === "approved") return <Build12ActionForm endpoint={`/api/admin/graduation/${confirmationId}/transition`} button="Complete Graduation Processing"><input type="hidden" name="action" value="complete" /><input name="actor_name" required placeholder="Named processing officer" className={field} /><textarea name="reason" required placeholder="Processing completion note" className={field} /></Build12ActionForm>;
  return null;
}

export function GraduationCancelForm({ confirmationId }: { confirmationId: string }) { return <Build12ActionForm endpoint={`/api/admin/graduation/${confirmationId}/cancel`} button="Cancel Confirmation"><input name="actor_name" required placeholder="Named authorised officer" className={field} /><textarea name="reason" required minLength={15} placeholder="Documented cancellation reason" className={field} /></Build12ActionForm>; }
export function AlumniConvertForm({ confirmationId }: { confirmationId: string }) { return <Build12ActionForm endpoint={`/api/admin/graduation/${confirmationId}/convert`} button="Convert Confirmed Graduate to Alumni"><input name="actor_name" required placeholder="Named conversion officer" className={field} /><p className="text-sm text-slate-600">This preserves all student history, reuses an alumni person record by student ID, and creates one programme completion record.</p></Build12ActionForm>; }
export function AwardCreateForm({ programmeId, templates }: { programmeId: string; templates: Record<string, unknown>[] }) { return <Build12ActionForm endpoint="/api/admin/awards" button="Create Primary Award Draft"><input type="hidden" name="alumni_programme_record_id" value={programmeId} /><input name="actor_name" required placeholder="Named award initiator" className={field} /><select name="certificate_template_id" required className={field}><option value="">Choose approved template</option>{templates.filter((template) => template.template_status === "approved").map((template) => <option key={String(template.id)} value={String(template.id)}>{String(template.template_name)} · v{String(template.template_version)}</option>)}</select><p className="text-sm text-amber-800">Draft templates and templates without approved signatures cannot create official awards.</p></Build12ActionForm>; }

export function AwardWorkflowForms({ award }: { award: Record<string, unknown> }) { const id = String(award.id); return <div className="grid gap-4 lg:grid-cols-2"><Build12ActionForm endpoint={`/api/admin/awards/${id}/generate`} button="Generate Private PDF"><input name="actor_name" required placeholder="Named document preparer" className={field} /><p className="text-sm text-slate-600">Uses the approved template, QR verification URL, approved signature assets and private storage.</p></Build12ActionForm><Build12ActionForm endpoint={`/api/admin/awards/${id}/transition`} button="Record Document Review"><input type="hidden" name="action" value="review" /><input name="actor_name" required placeholder="Named document reviewer" className={field} /><textarea name="reason" required minLength={10} placeholder="Document review note" className={field} /></Build12ActionForm><Build12ActionForm endpoint={`/api/admin/awards/${id}/transition`} button="Approve Award"><input type="hidden" name="action" value="approve" /><input name="actor_name" required placeholder="Named approver (different from reviewer)" className={field} /><textarea name="reason" required minLength={10} placeholder="Approval basis" className={field} /></Build12ActionForm><Build12ActionForm endpoint={`/api/admin/awards/${id}/transition`} button="Issue Award"><input type="hidden" name="action" value="issue" /><input name="actor_name" required placeholder="Named issuer (different from approver)" className={field} /><textarea name="reason" placeholder="Issuance note" className={field} /></Build12ActionForm></div>; }

export function AwardCorrectionForm({ awardId }: { awardId: string }) { return <Build12ActionForm endpoint={`/api/admin/awards/${awardId}/correct`} button="Prepare Corrected Award"><input name="actor_name" required placeholder="Named correction initiator" className={field} /><textarea name="reason" required minLength={15} placeholder="Correction reason; correct the official student identity first" className={field} /><input name="decision_reference" required placeholder="Correction decision reference" className={field} /></Build12ActionForm>; }
export function AwardRevocationForm({ awardId }: { awardId: string }) { return <Build12ActionForm endpoint={`/api/admin/awards/${awardId}/revoke`} button="Record Authorised Revocation"><input name="actor_name" required placeholder="Named authorised decision maker" className={field} /><textarea name="basis" required minLength={20} placeholder="Documented authorised basis" className={field} /><input name="decision_reference" required placeholder="Decision reference" className={field} /><textarea name="communication_record" required minLength={10} placeholder="How and when the alumnus was informed" className={field} /></Build12ActionForm>; }
export function TemplateApprovalForm({ templateId }: { templateId: string }) { return <Build12ActionForm endpoint={`/api/admin/awards/templates/${templateId}/approve`} button="Approve Certificate Template"><input name="actor_name" required placeholder="Named template approver" className={field} /><input name="approval_reference" required placeholder="Template approval reference" className={field} /><p className="text-sm text-amber-800">Approval is blocked unless every signatory name, role, approved flag and signature asset path is configured, and the claim contains no prohibited qualification language.</p></Build12ActionForm>; }

export function AnnouncementForm() { return <Build12ActionForm endpoint="/api/admin/alumni/announcements" button="Save Announcement"><input name="actor_name" required placeholder="Named announcement owner" className={field} /><input name="title" required placeholder="Announcement title" className={field} /><input name="summary" required placeholder="Short summary" className={field} /><textarea name="body" required minLength={20} placeholder="Announcement details" className={field} /><div className="grid gap-3 sm:grid-cols-2"><select name="announcement_type" className={field}>{["general", "further_training", "advanced_programme", "event", "service_opportunity", "career_or_project_opportunity", "institutional_update"].map((value) => <option key={value}>{value}</option>)}</select><select name="target_scope" className={field}>{["all_alumni", "cohort", "discipleship_route", "skill_pathway"].map((value) => <option key={value}>{value}</option>)}</select><input name="target_value" placeholder="Target cohort, route or pathway value" className={field} /><select name="announcement_status" className={field}><option value="draft">Draft</option><option value="published">Publish now</option></select><input name="expires_at" type="datetime-local" className={field} /><input name="call_to_action_label" placeholder="Optional link label" className={field} /><input name="call_to_action_url" placeholder="Optional https:// link or /register path" className={field} /></div></Build12ActionForm>; }

export function ArchiveRefreshForm({ programmeId }: { programmeId: string }) { return <Build12ActionForm endpoint={`/api/admin/alumni/programmes/${programmeId}/archive`} button="Initialise / Refresh Archive"><input name="actor_name" required placeholder="Named archive officer" className={field} /><p className="text-sm text-slate-600">Idempotently adds compatible completed courses and newly published summary versions without overwriting history.</p></Build12ActionForm>; }
export function RecordingGrantForm({ alumniId, archives, recordings }: { alumniId: string; archives: Record<string, unknown>[]; recordings: Record<string, unknown>[] }) { return <Build12ActionForm endpoint={`/api/admin/alumni/${alumniId}/recording-grants`} button="Grant Recording Access"><input name="actor_name" required placeholder="Named access approver" className={field} /><select name="alumni_course_archive_id" required className={field}><option value="">Choose archived course</option>{archives.map((archive) => <option key={String(archive.id)} value={String(archive.id)}>{String(archive.course_code_snapshot)} · {String(archive.course_title_snapshot)}</option>)}</select><select name="class_recording_id" required className={field}><option value="">Choose recording from an archived course</option>{recordings.map((recording) => <option key={String(recording.id)} value={String(recording.id)}>{String(recording.title)}</option>)}</select><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Available from<input name="available_from" type="datetime-local" className={field} /></label><label className="text-sm font-semibold">Available until<input name="available_until" type="datetime-local" className={field} /></label></div><textarea name="grant_reason" required minLength={10} placeholder="Controlled access reason" className={field} /></Build12ActionForm>; }
export function RecordingRevokeForm({ grantId }: { grantId: string }) { return <Build12ActionForm endpoint={`/api/admin/alumni/recording-grants/${grantId}/revoke`} button="Revoke Recording Access"><input name="actor_name" required placeholder="Named access officer" className={field} /><textarea name="reason" required minLength={10} placeholder="Revocation reason" className={field} /></Build12ActionForm>; }
