"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";

import { academicStandings, noticeTypes, recoveryPlanStatuses, reviewOutcomes, reviewStatuses, reviewTypes } from "@/lib/lms/engagement";

type Option = { id: string; label: string };

async function jsonRequest(url: string, method: string, body?: Record<string, unknown>) { const response = await fetch(url, { method, headers: body ? { "Content-Type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.message || "The request could not be completed."); return payload; }
function FormButton({ busy, children }: { busy: boolean; children: React.ReactNode }) { return <button disabled={busy} className="rounded-xl bg-[#071327] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{children}</button>; }
const input = "min-h-11 w-full rounded-xl border border-slate-300 px-3 text-sm";
const textarea = "w-full rounded-xl border border-slate-300 p-3 text-sm";

export function EvaluateEngagementButton({ studentEnrollmentId, cohortId }: { studentEnrollmentId?: string; cohortId?: string }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function evaluate() { setBusy(true); setMessage(""); try { const result = studentEnrollmentId ? await jsonRequest("/api/admin/engagement/evaluate", "POST", { student_enrollment_id: studentEnrollmentId }) : await jsonRequest("/api/admin/engagement/evaluate-cohort", "POST", { cohort_id: cohortId }); setMessage(`Evaluation complete: ${result.created ?? 0} new, ${result.updated ?? 0} updated, ${result.resolved ?? 0} resolved${result.students ? ` across ${result.students} students` : ""}.`); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Evaluation failed."); } finally { setBusy(false); } }
  return <div><button type="button" disabled={busy || (!studentEnrollmentId && !cohortId)} onClick={evaluate} className="rounded-xl border border-amber-500 bg-amber-50 px-4 py-2.5 text-sm font-semibold text-amber-950 disabled:opacity-50">{busy ? "Evaluating…" : studentEnrollmentId ? "Evaluate This Student" : "Evaluate Current Cohort"}</button>{message ? <p role="status" className="mt-2 max-w-xl text-xs text-slate-600">{message}</p> : null}</div>;
}

export function MentorAssignmentForm({ studentEnrollmentId, mentors }: { studentEnrollmentId: string; mentors: Option[] }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const values = Object.fromEntries(new FormData(event.currentTarget)); try { await jsonRequest(`/api/admin/students/${studentEnrollmentId}/mentor`, "POST", values); setMessage("Mentor assignment saved."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Mentor could not be assigned."); } finally { setBusy(false); } }
  return <form onSubmit={submit} className="grid gap-3"><select name="mentor_profile_id" required className={input}><option value="">Select authorised mentor</option>{mentors.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select><input name="reason" required maxLength={1000} placeholder="Reason for assignment or change" className={input} /><FormButton busy={busy}>Assign Mentor</FormButton>{message ? <p role="status" className="text-xs text-slate-600">{message}</p> : null}</form>;
}

export function NoticeForm({ studentEnrollmentId, alerts }: { studentEnrollmentId: string; alerts: Option[] }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const form = new FormData(event.currentTarget); const body = Object.fromEntries(form); body.alert_ids = form.getAll("alert_ids") as never; try { await jsonRequest("/api/admin/warnings", "POST", { ...body, student_enrollment_id: studentEnrollmentId }); setMessage("Draft notice created. Review it below before issuing."); event.currentTarget.reset(); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Notice draft could not be created."); } finally { setBusy(false); } }
  return <form onSubmit={submit} className="grid gap-3"><select name="notice_type" required className={input}>{noticeTypes.map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select><input name="title" required maxLength={180} placeholder="Clear notice title" className={input} /><textarea name="reason_summary" required maxLength={4000} rows={3} placeholder="Factual reason summary—no accusations or private welfare detail" className={textarea} /><textarea name="required_action" maxLength={4000} rows={2} placeholder="Required action and available support route" className={textarea} /><label className="text-sm font-medium">Response deadline<input name="response_due_at" type="datetime-local" className={`mt-1 ${input}`} /></label>{alerts.length ? <fieldset className="space-y-2 rounded-xl border border-slate-200 p-3"><legend className="px-1 text-xs font-semibold uppercase text-slate-500">Link relevant alerts</legend>{alerts.map((item) => <label key={item.id} className="flex gap-2 text-sm"><input type="checkbox" name="alert_ids" value={item.id} />{item.label}</label>)}</fieldset> : null}<FormButton busy={busy}>Create Draft Notice</FormButton>{message ? <p role="status" className="text-xs text-slate-600">{message}</p> : null}</form>;
}

export function NoticeWorkflowButtons({ noticeId, status }: { noticeId: string; status: string }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function issue() { if (!window.confirm("Issue this reviewed notice to the student? In-app delivery will be recorded and an email will be attempted.")) return; setBusy(true); try { await jsonRequest(`/api/admin/warnings/${noticeId}/issue`, "POST"); setMessage("Notice issued; in-app delivery recorded and email attempted."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Notice could not be issued."); } finally { setBusy(false); } }
  async function resolve() { const note = window.prompt("Resolution note"); if (!note) return; setBusy(true); try { await jsonRequest(`/api/admin/warnings/${noticeId}/resolve`, "POST", { resolution_note: note }); setMessage("Notice resolved; history preserved."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Notice could not be resolved."); } finally { setBusy(false); } }
  return <div className="mt-3 flex flex-wrap gap-2">{status === "draft" ? <button disabled={busy} onClick={issue} className="rounded-lg bg-[#071327] px-3 py-2 text-xs font-semibold text-white">Issue Notice</button> : null}{!["draft", "resolved", "withdrawn"].includes(status) ? <button disabled={busy} onClick={resolve} className="rounded-lg border border-slate-300 px-3 py-2 text-xs font-semibold">Resolve</button> : null}{message ? <p className="w-full text-xs text-slate-600">{message}</p> : null}</div>;
}

export function StandingChangeForm({ studentEnrollmentId, notices, cases, current }: { studentEnrollmentId: string; notices: Option[]; cases: Option[]; current: string }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); if (!window.confirm(`Change this student's academic standing from ${current.replaceAll("_", " ")} to ${String(values.new_standing ?? "the selected standing").replaceAll("_", " ")}? The reason and linked evidence will be recorded.`)) return; setBusy(true); try { await jsonRequest(`/api/admin/student-enrollments/${studentEnrollmentId}/standing`, "POST", values); setMessage("Academic standing changed and history recorded."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Standing could not be changed."); } finally { setBusy(false); } }
  return <form onSubmit={submit} className="grid gap-3"><select name="new_standing" defaultValue={current} className={input}>{academicStandings.map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select><textarea name="reason" required rows={2} maxLength={4000} placeholder="Required reason" className={textarea} /><select name="linked_warning_notice_id" className={input}><option value="">Link notice where relevant</option>{notices.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select><select name="linked_review_case_id" className={input}><option value="">Link review case where relevant</option>{cases.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select><FormButton busy={busy}>Change Standing</FormButton>{message ? <p className="text-xs text-slate-600">{message}</p> : null}</form>;
}

export function RecoveryPlanForm({ studentEnrollmentId, mentorAssignmentId, noticeOptions }: { studentEnrollmentId: string; mentorAssignmentId?: string; noticeOptions: Option[] }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const values = Object.fromEntries(new FormData(event.currentTarget)); const body = { ...values, student_enrollment_id: studentEnrollmentId, mentor_assignment_id: mentorAssignmentId, actions: [{ action_type: values.action_type, title: values.action_title, description: values.action_description, linked_entity_type: values.linked_entity_type || null, linked_entity_id: values.linked_entity_id || null, due_at: values.action_due_at || null }] }; try { await jsonRequest("/api/admin/recovery-plans", "POST", body); setMessage("Draft recovery plan created with a concrete action."); event.currentTarget.reset(); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Recovery plan could not be created."); } finally { setBusy(false); } }
  return <form onSubmit={submit} className="grid gap-3"><input name="plan_title" required placeholder="Plan title" className={input} /><textarea name="reason_summary" required rows={2} placeholder="Factual reason and recovery purpose" className={textarea} /><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Start date<input name="start_date" type="date" className={`mt-1 ${input}`} /></label><label className="text-sm">Target date<input name="target_completion_date" type="date" className={`mt-1 ${input}`} /></label></div><select name="warning_notice_id" className={input}><option value="">Optional linked notice</option>{noticeOptions.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select><div className="rounded-xl border border-slate-200 p-3"><p className="mb-2 text-xs font-semibold uppercase text-slate-500">First concrete action</p><input name="action_title" required placeholder="e.g. Complete Session 2 recorded learning" className={input} /><textarea name="action_description" rows={2} placeholder="What completion requires" className={`mt-2 ${textarea}`} /><input type="hidden" name="action_type" value="academic_action" /><div className="mt-2 grid gap-2 sm:grid-cols-2"><select name="linked_entity_type" className={input}><option value="">No linked record</option>{["recording", "makeup", "assignment", "quiz"].map((value) => <option key={value}>{value}</option>)}</select><input name="linked_entity_id" placeholder="Linked record UUID" className={input} /></div><input name="action_due_at" type="datetime-local" className={`mt-2 ${input}`} /></div><FormButton busy={busy}>Create Draft Recovery Plan</FormButton>{message ? <p className="text-xs text-slate-600">{message}</p> : null}</form>;
}

export function RecoveryPlanStatusForm({ planId, current }: { planId: string; current: string }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const values = Object.fromEntries(new FormData(event.currentTarget)); try { await jsonRequest(`/api/admin/recovery-plans/${planId}`, "PATCH", values); setMessage("Plan status updated after authorised review."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Plan could not be updated."); } finally { setBusy(false); } }
  return <form onSubmit={submit} className="mt-3 grid gap-2"><select name="plan_status" defaultValue={current} className={input}>{recoveryPlanStatuses.map((value) => <option key={value}>{value}</option>)}</select><input name="closure_note" placeholder="Required for completion or closure" className={input} /><FormButton busy={busy}>Update Plan</FormButton>{message ? <p className="text-xs text-slate-600">{message}</p> : null}</form>;
}

export function ReviewCaseForm({ studentEnrollmentId }: { studentEnrollmentId: string }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const values = Object.fromEntries(new FormData(event.currentTarget)); try { await jsonRequest("/api/admin/review-cases", "POST", { ...values, student_enrollment_id: studentEnrollmentId, notify_student: true }); setMessage("Review case opened and made available for student response."); event.currentTarget.reset(); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Review case could not be opened."); } finally { setBusy(false); } }
  return <form onSubmit={submit} className="grid gap-3"><select name="review_type" className={input}>{reviewTypes.map((value) => <option key={value}>{value}</option>)}</select><input name="case_title" required placeholder="Review case title" className={input} /><textarea name="concern_summary" required rows={3} placeholder="Factual concern visible to the student" className={textarea} /><textarea name="evidence_summary" rows={2} placeholder="Evidence in substance; exclude third-party confidential detail" className={textarea} /><label className="text-sm">Response deadline<input name="response_due_at" type="datetime-local" required className={`mt-1 ${input}`} /></label><FormButton busy={busy}>Open Review Case</FormButton>{message ? <p className="text-xs text-slate-600">{message}</p> : null}</form>;
}

export function ReviewCaseUpdateForm({ caseId, currentStatus }: { caseId: string; currentStatus: string }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const values = Object.fromEntries(new FormData(event.currentTarget)); if (!values.decision_outcome) delete values.decision_outcome; try { await jsonRequest(`/api/admin/review-cases/${caseId}`, "PATCH", values); setMessage("Review case updated. Recommendations did not change enrolment status."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Review case could not be updated."); } finally { setBusy(false); } }
  return <form onSubmit={submit} className="mt-3 grid gap-2"><select name="case_status" defaultValue={currentStatus} className={input}>{reviewStatuses.map((value) => <option key={value}>{value}</option>)}</select><select name="decision_outcome" className={input}><option value="">No decision yet</option>{reviewOutcomes.map((value) => <option key={value}>{value}</option>)}</select><textarea name="decision_rationale" rows={2} placeholder="Required with a decision" className={textarea} /><textarea name="private_note" rows={2} placeholder="Optional private admin note (restricted)" className={textarea} /><FormButton busy={busy}>Update Review</FormButton>{message ? <p className="text-xs text-slate-600">{message}</p> : null}</form>;
}
