"use client";

import { useState } from "react";
import { AdminPanel, DataItem, StatusBadge, formatDate } from "@/components/admin/LmsUi";
import { assignmentRoles, facilitatorStatuses, humanize } from "@/lib/lms/adminConstants";
import type { fetchAdminFacilitator } from "@/lib/lms/adminData";

type RecordData = Awaited<ReturnType<typeof fetchAdminFacilitator>>;
function object(value: unknown) { return value && typeof value === "object" ? value as Record<string, unknown> : {}; }
function text(value: unknown) { return typeof value === "string" ? value : null; }

export function FacilitatorRecord({ initialRecord }: { initialRecord: RecordData }) {
  const [record, setRecord] = useState(initialRecord); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const response = await fetch(`/api/admin/facilitators/${record.facilitator.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); const payload = await response.json(); setBusy(false); if (!response.ok) return setMessage(payload.message || "Facilitator could not be updated."); setRecord((current) => ({ ...current, facilitator: payload.facilitator })); setMessage("Facilitator updated."); }
  async function assign(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const response = await fetch(`/api/admin/facilitators/${record.facilitator.id}/assignments`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); const payload = await response.json(); setBusy(false); if (!response.ok) return setMessage(payload.message || "Assignment could not be saved."); setRecord((current) => ({ ...current, assignments: [...current.assignments, payload.assignment] })); setMessage("Facilitator assigned."); }
  async function remove(id: string) { if (!window.confirm("Remove this facilitator from the cohort course?")) return; setBusy(true); const response = await fetch(`/api/admin/facilitators/${record.facilitator.id}/assignments/${id}`, { method: "DELETE" }); const payload = await response.json(); setBusy(false); if (!response.ok) return setMessage(payload.message || "Assignment could not be removed."); setRecord((current) => ({ ...current, assignments: current.assignments.filter((item) => item.id !== id) })); setMessage("Assignment removed."); }
  async function sendPortalAccess(mode: "activation" | "recovery" = "activation") { if (!record.facilitator.email) return setMessage("Add an approved facilitator email first."); if (!window.confirm(`${mode === "recovery" ? "Send password reset / account recovery" : "Send portal activation or access reminder"} to ${record.facilitator.email}?`)) return; setBusy(true); setMessage(""); const response = await fetch(`/api/admin/facilitators/${record.facilitator.id}/portal-access`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mode }) }); const payload = await response.json(); setBusy(false); if (payload.portalAccount) setRecord((current) => ({ ...current, portalAccount: payload.portalAccount })); setMessage(response.ok ? payload.message || "Portal access email sent." : payload.message || "Portal access could not be sent."); }
  const assignedOfferingIds = new Set(record.assignments.map((item) => item.cohort_course_id));
  return <div className="space-y-6">{message ? <p role="status" className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950">{message}</p> : null}<AdminPanel title="Facilitator profile"><form onSubmit={save} className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">Display name<input name="display_name" required defaultValue={record.facilitator.display_name} className="mt-1 block w-full rounded-xl border border-slate-300 px-3 py-2" /></label><label className="text-sm font-medium">Title<input name="title" defaultValue={record.facilitator.title ?? ""} className="mt-1 block w-full rounded-xl border border-slate-300 px-3 py-2" /></label><label className="text-sm font-medium">Email<input name="email" type="email" defaultValue={record.facilitator.email ?? ""} className="mt-1 block w-full rounded-xl border border-slate-300 px-3 py-2" /></label><label className="text-sm font-medium">Phone<input name="phone" defaultValue={record.facilitator.phone ?? ""} className="mt-1 block w-full rounded-xl border border-slate-300 px-3 py-2" /></label><label className="text-sm font-medium">Status<select name="facilitator_status" defaultValue={record.facilitator.facilitator_status} className="mt-1 block w-full rounded-xl border border-slate-300 px-3 py-2">{facilitatorStatuses.map((item) => <option key={item} value={item}>{humanize(item)}</option>)}</select></label><label className="text-sm font-medium md:col-span-2">Biography<textarea name="bio" defaultValue={record.facilitator.bio ?? ""} rows={4} className="mt-1 block w-full rounded-xl border border-slate-300 p-3" /></label><label className="text-sm font-medium md:col-span-2">Internal notes<textarea name="internal_notes" defaultValue={record.facilitator.internal_notes ?? ""} rows={3} className="mt-1 block w-full rounded-xl border border-slate-300 p-3" /></label><button disabled={busy} className="rounded-xl bg-[#071327] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50 md:col-span-2">Save facilitator</button></form></AdminPanel>
    <AdminPanel title="Portal access" description="Portal status is derived from Supabase Auth password evidence and successful email audit events."><dl className="grid gap-5 sm:grid-cols-2"><DataItem label="Portal Account"><StatusBadge value={record.portalAccount.label} /></DataItem><DataItem label="Last Portal Invitation">{record.portalAccount.lastPortalInvitationAt ? formatDate(record.portalAccount.lastPortalInvitationAt, true) : "Not sent"}</DataItem></dl><div className="mt-6 flex flex-wrap gap-3"><button disabled={busy || !record.facilitator.email} onClick={() => sendPortalAccess("activation")} className="rounded-xl bg-[#071327] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{record.portalAccount.status === "account_active" ? "Send Portal Access Reminder" : "Send / Resend Account Activation"}</button><button disabled={busy || record.portalAccount.status === "not_provisioned"} onClick={() => sendPortalAccess("recovery")} className="rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-[#071327] disabled:opacity-50">Password Reset / Account Recovery</button></div></AdminPanel>
    <AdminPanel title="Course assignments" description="Assignments grant access only to explicitly assigned cohort-course spaces."><form onSubmit={assign} className="mb-5 grid gap-3 md:grid-cols-[1fr_180px_auto]"><select name="cohortCourseId" required defaultValue="" className="rounded-xl border border-slate-300 px-3 py-2 text-sm"><option value="" disabled>Select a cohort course</option>{record.availableOfferings.filter((item) => !assignedOfferingIds.has(item.id)).map((raw) => { const course = object(raw.courses); const cohort = object(raw.cohorts); return <option key={raw.id} value={raw.id}>{text(cohort.code)} · {text(course.code)} · {text(course.title)}</option>; })}</select><select name="assignmentRole" defaultValue="lead" className="rounded-xl border border-slate-300 px-3 py-2 text-sm">{assignmentRoles.map((item) => <option key={item} value={item}>{humanize(item)}</option>)}</select><button disabled={busy} className="rounded-xl bg-[#071327] px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Assign</button></form>{record.assignments.length === 0 ? <p className="text-sm text-slate-600">No cohort courses are assigned.</p> : <div className="space-y-3">{record.assignments.map((raw) => { const offering = object(raw.cohort_courses); const course = object(offering.courses); const cohort = object(offering.cohorts); return <div key={raw.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 p-4"><div><strong>{text(course.code)} · {text(course.title)}</strong><p className="mt-1 text-sm text-slate-600">{text(cohort.code)} · {text(cohort.name)}</p></div><div className="flex items-center gap-3"><StatusBadge value={raw.assignment_role} /><button disabled={busy} onClick={() => remove(raw.id)} className="rounded-lg border border-rose-200 px-3 py-1.5 text-xs font-semibold text-rose-800">Remove</button></div></div>; })}</div>}</AdminPanel>
  </div>;
}
