"use client";

import { useRouter } from "next/navigation";
import { type FormEvent, type ReactNode, useState } from "react";

const field = "min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm";

function payload(form: HTMLFormElement) {
  const result: Record<string, unknown> = {};
  for (const [key, value] of new FormData(form)) result[key] = value;
  return result;
}

export function ResultActionForm({ endpoint, button, children, compact = false, confirmation }: { endpoint: string; button: string; children?: ReactNode; compact?: boolean; confirmation?: string }) {
  const router = useRouter(); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (confirmation && !window.confirm(confirmation)) return; setBusy(true); setMessage(""); try { const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload(event.currentTarget)) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message || "The action could not be completed."); setMessage("Saved."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "The action could not be completed."); } finally { setBusy(false); } }
  return <form onSubmit={submit} className={compact ? "space-y-2" : "space-y-3 rounded-2xl border border-slate-200 bg-white p-4"}>{children}{message ? <p role="status" className="text-sm text-amber-800">{message}</p> : null}<button disabled={busy} className="min-h-11 rounded-xl bg-[#071327] px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{busy ? "Working…" : button}</button></form>;
}

export function CalculateResultButton({ studentEnrollmentId }: { studentEnrollmentId: string }) { return <ResultActionForm endpoint="/api/admin/results/calculate" button="Calculate / Recalculate Result" compact><input type="hidden" name="student_enrollment_id" value={studentEnrollmentId} /></ResultActionForm>; }
export function CalculateCohortButton({ cohortId }: { cohortId: string }) { return <ResultActionForm endpoint="/api/admin/results/calculate" button="Calculate Current Cohort" compact><input type="hidden" name="cohort_id" value={cohortId} /></ResultActionForm>; }
export function InitialiseEngagementButton({ studentEnrollmentId }: { studentEnrollmentId: string }) { return <ResultActionForm endpoint="/api/admin/results/engagement/initialise" button="Prepare Engagement Evidence" compact><input type="hidden" name="student_enrollment_id" value={studentEnrollmentId} /></ResultActionForm>; }

export function WeightingForm({ categories, assignments, quizzes }: { categories: Record<string, unknown>[]; assignments: Record<string, unknown>[]; quizzes: Record<string, unknown>[] }) {
  const [categoryId, setCategoryId] = useState(""); const [assessmentKey, setAssessmentKey] = useState(""); const [attemptSelection, setAttemptSelection] = useState("best_graded");
  const category = categories.find((item) => item.id === categoryId); const [assessmentType, assessmentId] = assessmentKey.split(":"); const assessment = (assessmentType === "assignment" ? assignments : quizzes).find((item) => item.id === assessmentId); const conflict = Boolean(category && assessment && (category.score_domain !== assessment.assessment_domain || category.category_code !== assessment.assessment_category));
  return <ResultActionForm endpoint="/api/admin/results/weightings" button="Save Assessment Weighting">
    <div className="grid gap-3 md:grid-cols-2"><label className="text-sm font-semibold">Score category<select name="score_category_id" value={categoryId} onChange={(event) => setCategoryId(event.target.value)} required className={field}><option value="">Choose category</option>{categories.map((item) => <option key={String(item.id)} value={String(item.id)}>{String(item.category_name)} · {String(item.max_points)} pts</option>)}</select></label><label className="text-sm font-semibold">Assignment or quiz<select value={assessmentKey} onChange={(event) => { setAssessmentKey(event.target.value); setAttemptSelection(event.target.value.startsWith("assignment:") ? "latest_graded" : "best_graded"); }} required className={field}><option value="">Choose assessment</option><optgroup label="Assignments">{assignments.map((item) => <option key={String(item.id)} value={`assignment:${String(item.id)}`}>{String(item.title)} · {String(item.assessment_category)}</option>)}</optgroup><optgroup label="Quizzes">{quizzes.map((item) => <option key={String(item.id)} value={`quiz:${String(item.id)}`}>{String(item.title)} · {String(item.assessment_category)}</option>)}</optgroup></select><input type="hidden" name="assessment_type" value={assessmentType ?? ""} /><input type="hidden" name="assessment_id" value={assessmentId ?? ""} /></label><label className="text-sm font-semibold">Relative weight within category<input name="weight_units" type="number" min="0.01" step="0.01" defaultValue="1" required className={field} /></label><label className="text-sm font-semibold">Attempt selection<select name="attempt_selection" value={attemptSelection} onChange={(event) => setAttemptSelection(event.target.value)} className={field}><option value="best_graded">Best graded</option><option value="latest_graded">Latest graded</option><option value="first_graded">First graded</option></select></label></div>
    <div className="grid gap-2 text-sm sm:grid-cols-2"><label><input type="hidden" name="is_required" value="false" /><input name="is_required" type="checkbox" defaultChecked /> Required assessment</label><label><input type="hidden" name="required_for_graduation" value="false" /><input name="required_for_graduation" type="checkbox" /> Required for graduation</label><label><input type="hidden" name="counts_toward_result" value="false" /><input name="counts_toward_result" type="checkbox" defaultChecked /> Counts toward result</label><label><input type="hidden" name="active" value="false" /><input name="active" type="checkbox" defaultChecked /> Active mapping</label></div>
    {conflict ? <div className="rounded-xl border-2 border-amber-400 bg-amber-50 p-3 text-sm text-amber-950"><strong>Mapping conflict:</strong> the assessment metadata is {String(assessment?.assessment_domain)} / {String(assessment?.assessment_category)}, while this score category is {String(category?.score_domain)} / {String(category?.category_code)}. Domain conflicts are rejected. A reviewed category-metadata conflict requires confirmation and a documented reason.<label className="mt-3 block"><input name="confirm_metadata_conflict" type="checkbox" /> Confirm reviewed metadata conflict</label><textarea name="conflict_reason" placeholder="Academic reason for this exceptional category mapping" className={`${field} mt-2`} /></div> : null}
  </ResultActionForm>;
}

export function EngagementReviewForm({ evaluation, facilitator = false }: { evaluation: Record<string, unknown>; facilitator?: boolean }) { const category = Array.isArray(evaluation.programme_score_categories) ? evaluation.programme_score_categories[0] : evaluation.programme_score_categories as Record<string, unknown> | undefined; return <ResultActionForm endpoint={`${facilitator ? "/api/facilitator" : "/api/admin"}/results/engagement/${String(evaluation.id)}`} button="Save Engagement Review" compact><div className="grid gap-2 md:grid-cols-2"><select name="action" className={field}>{facilitator ? <option value="evaluate">Evaluate Assigned-Course Evidence</option> : <><option value="evaluate">Evaluate</option><option value="moderate">Moderate</option><option value="approve">Approve</option></>}</select><input name="reviewer_name" placeholder="Named reviewer" required className={field} /><input name="awarded_points" type="number" min="0" max={Number(category?.max_points ?? 0)} step="0.01" defaultValue={String(evaluation.awarded_points ?? evaluation.suggested_points ?? "")} placeholder={`Points / ${String(category?.max_points ?? "")}`} className={field} /><textarea name="evidence_summary" placeholder={facilitator ? "Evidence summary from your assigned course (minimum 20 characters)" : "Evidence summary (required for evaluation)"} defaultValue={String(evaluation.evidence_summary ?? "")} className={field} />{facilitator ? null : <textarea name="moderation_note" placeholder="Moderation evidence and reason" className={field} />}</div></ResultActionForm>; }

export function RequirementOverrideForm({ requirementId }: { requirementId: string }) { return <ResultActionForm endpoint={`/api/admin/results/requirements/${requirementId}/override`} button="Record Authorised Override" compact><select name="requirement_status" className={field}><option value="met">Met</option><option value="not_met">Not Met</option><option value="under_review">Under Review</option><option value="waived">Waived</option><option value="not_applicable">Not Applicable</option></select><input name="reviewer_name" placeholder="Authorised reviewer" required className={field} /><textarea name="reason" placeholder="Documented evidence and reason (minimum 20 characters)" required className={field} /></ResultActionForm>; }

export function ComponentModerationForm({ component }: { component: Record<string, unknown> }) { return <ResultActionForm endpoint={`/api/admin/results/components/${String(component.id)}/moderate`} button="Record Moderation" compact><input name="moderated_points" type="number" min="0" max={Number(component.maximum_points)} step="0.01" required placeholder={`Points / ${String(component.maximum_points)}`} className={field} /><input name="reviewer_name" placeholder="Named moderator" required className={field} /><textarea name="moderation_note" placeholder="Evidence and reason; arbitrary marks are prohibited" required className={field} /></ResultActionForm>; }

export function CapstoneDefenceForm({ studentEnrollmentId, assignments, facilitator = false }: { studentEnrollmentId: string; assignments: Record<string, unknown>[]; facilitator?: boolean }) { const [assignmentId, setAssignmentId] = useState(""); const selected = assignments.find((item) => item.id === assignmentId); const submissions = (selected?.assignment_submissions ?? []) as Record<string, unknown>[]; return <ResultActionForm endpoint={`${facilitator ? "/api/facilitator" : "/api/admin"}/results/capstone-defences`} button="Save Capstone Defence"><input type="hidden" name="student_enrollment_id" value={studentEnrollmentId} /><div className="grid gap-3 md:grid-cols-2"><select name="capstone_assignment_id" value={assignmentId} onChange={(event) => setAssignmentId(event.target.value)} required className={field}><option value="">Choose capstone</option>{assignments.map((item) => <option key={String(item.id)} value={String(item.id)}>{String(item.title)}</option>)}</select><select name="assignment_submission_id" className={field}><option value="">Accepted submission</option>{submissions.filter((item) => item.submission_status === "graded" && item.review_outcome === "accepted").map((item) => <option key={String(item.id)} value={String(item.id)}>Attempt {String(item.attempt_number)} · {String(item.score_percentage)}%</option>)}</select><select name="defence_status" className={field}><option value="not_scheduled">Not Scheduled</option><option value="scheduled">Scheduled</option><option value="completed">Completed</option><option value="reschedule_required">Reschedule Required</option><option value="cancelled">Cancelled</option></select><select name="defence_outcome" className={field}><option value="">No outcome yet</option><option value="passed">Passed</option><option value="revision_required">Revision Required</option><option value="not_passed">Not Passed</option></select><input name="scheduled_at" type="datetime-local" className={field} /><input name="completed_at" type="datetime-local" className={field} /><input name="panel_members" required placeholder="Panel members, comma-separated" className={field} /><textarea name="defence_note" placeholder="Academic note" className={field} /></div></ResultActionForm>; }

export function BatchCreateForm({ cohorts }: { cohorts: Record<string, unknown>[] }) { return <ResultActionForm endpoint="/api/admin/results/batches" button="Create Result Batch"><select name="cohort_id" required className={field}><option value="">Choose cohort</option>{cohorts.map((cohort) => <option key={String(cohort.id)} value={String(cohort.id)}>{String(cohort.code)} · {String(cohort.name)}</option>)}</select><input name="batch_name" required placeholder="e.g. August 2026 Cohort Final Results" className={field} /><textarea name="notes" placeholder="Preparation notes" className={field} /></ResultActionForm>; }
export function AddBatchItemForm({ batchId, results }: { batchId: string; results: Record<string, unknown>[] }) { return <ResultActionForm endpoint={`/api/admin/results/batches/${batchId}/items`} button="Add Result"><select name="student_programme_result_id" required className={field}><option value="">Choose calculated result</option>{results.map((result) => { const enrollment = Array.isArray(result.student_enrollments) ? result.student_enrollments[0] : result.student_enrollments as Record<string, unknown>; const student = Array.isArray(enrollment?.students) ? enrollment.students[0] : enrollment?.students as Record<string, unknown>; return <option key={String(result.id)} value={String(result.id)}>{String(student?.student_number)} · {String(student?.preferred_name || student?.legal_name)} · {String(result.result_outcome)}</option>; })}</select></ResultActionForm>; }
export function BatchTransitionForm({ batchId, status }: { batchId: string; status: string }) { const action = status === "draft" ? "prepare" : status === "prepared" ? "submit" : status === "submitted_for_review" ? "review" : status === "reviewed" ? "approve" : status === "approved" ? "publish" : null; if (!action) return null; const confirmation = action === "approve" ? "Approve this result batch after confirming the authority references and reviewed evidence?" : action === "publish" ? "Publish this approved result batch to every included student? This also attempts the result notification emails." : undefined; return <ResultActionForm endpoint={`/api/admin/results/batches/${batchId}/transition`} button={`${action[0].toUpperCase()}${action.slice(1)} Batch`} confirmation={confirmation}><input type="hidden" name="action" value={action} /><input name="reviewer_name" required placeholder="Named authorised reviewer / approver" className={field} />{action === "approve" ? <><input name="approval_reference" required placeholder="Batch approval reference" className={field} /><input name="authority_reference" required placeholder="Academic Council / authorised authority reference" className={field} /><input name="approval_date" type="date" className={field} /><textarea name="notes" placeholder="Approval notes" className={field} /></> : null}{action === "publish" ? <p className="text-sm text-amber-900">Publication makes every included result visible to its student and attempts a secure-portal email notification.</p> : null}</ResultActionForm>; }

export function WithholdForm({ resultId }: { resultId: string }) { return <ResultActionForm endpoint={`/api/admin/results/programme/${resultId}/withhold`} button="Withhold Result" confirmation="Withhold this result using the documented legitimate reason and student communication entered here?"><textarea name="reason" required placeholder="Legitimate documented reason; hidden fees are not a valid reason" className={field} /><textarea name="student_communication" required placeholder="Student-facing communication" className={field} /></ResultActionForm>; }
export function CorrectionForm({ result }: { result: Record<string, unknown> }) { return <ResultActionForm endpoint={`/api/admin/results/programme/${String(result.id)}/correct`} button="Record Approved Correction" confirmation="Record this approved correction? The published result will become non-public until it passes the controlled approval and publication workflow again."><div className="grid gap-3 md:grid-cols-2"><input name="discipleship_points" type="number" min="0" max="40" step="0.01" defaultValue={String(result.discipleship_points ?? "")} required className={field} /><input name="skill_points" type="number" min="0" max="45" step="0.01" defaultValue={String(result.skill_points ?? "")} required className={field} /><input name="engagement_points" type="number" min="0" max="15" step="0.01" defaultValue={String(result.engagement_points ?? "")} required className={field} /><select name="result_outcome" defaultValue={String(result.result_outcome ?? "not_yet_eligible")} className={field}>{["eligible_for_completion", "not_yet_eligible", "incomplete", "resit_required", "deferred_result", "failed", "withheld", "under_review"].map((value) => <option key={value}>{value}</option>)}</select><input name="initiator" required placeholder="Correction initiator" className={field} /><input name="approver" required placeholder="Different authorised approver" className={field} /><textarea name="correction_reason" required placeholder="Correction reason" className={field} /><textarea name="evidence" required placeholder="Correction evidence" className={field} /></div><p className="text-sm text-amber-900">A corrected published result becomes non-public until it is approved and published in a controlled batch. The original snapshot is preserved.</p></ResultActionForm>; }
