"use client";
/* eslint-disable react-hooks/purity -- past/upcoming styling is display-only and is evaluated from the current browser clock */

import Link from "next/link";
import { useMemo, useState } from "react";

import { EmptyState, StatusBadge, formatDate } from "@/components/admin/LmsUi";
import { courseCategories, humanize, sessionDeliveryModes, sessionStatuses, sessionTypes, sessionVisibilityStatuses } from "@/lib/lms/adminConstants";
import type { fetchAdminSessions, fetchSessionOptions, SessionFilters } from "@/lib/lms/sessionData";

type Sessions = Awaited<ReturnType<typeof fetchAdminSessions>>; type Options = Awaited<ReturnType<typeof fetchSessionOptions>>;
const sessionTableColumns = [
  { key: "scheduled-at", label: "Date / time" },
  { key: "session-title", label: "Session" },
  { key: "course", label: "Course" },
  { key: "cohort", label: "Cohort" },
  { key: "facilitator", label: "Facilitator" },
  { key: "delivery-mode", label: "Delivery" },
  { key: "session-status", label: "Status" },
  { key: "summary-status", label: "Summary" },
  { key: "recording-status", label: "Recording" },
] as const;

export function SessionsManager({ initialSessions, options, filters }: { initialSessions: Sessions; options: Options; filters: SessionFilters }) {
  const [sessions, setSessions] = useState(initialSessions); const [showCreate, setShowCreate] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [selectedOffering, setSelectedOffering] = useState("");
  const cohortOptions = useMemo(() => { const map = new Map<string, string>(); options.offerings.forEach((raw) => { const cohort = relation(object(raw).cohorts); if (text(cohort.id)) map.set(text(cohort.id)!, `${text(cohort.code)} · ${text(cohort.name)}`); }); return [...map]; }, [options.offerings]);
  const courseOptions = useMemo(() => { const map = new Map<string, string>(); options.offerings.forEach((raw) => { const course = relation(object(raw).courses); if (text(course.id)) map.set(text(course.id)!, `${text(course.code)} · ${text(course.title)}`); }); return [...map]; }, [options.offerings]);
  const suggestion = options.offerings.find((item) => item.id === selectedOffering);
  async function create(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const form = new FormData(event.currentTarget); const body: Record<string, unknown> = Object.fromEntries(form); body.is_required = form.get("is_required") === "on"; const response = await fetch("/api/admin/sessions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json(); setBusy(false); if (!response.ok) return setMessage(payload.message || "Class session could not be created."); setSessions((current) => [payload.session, ...current]); setMessage("Class session created."); setShowCreate(false); window.location.href = `/admin/sessions/${payload.session.id}`; }
  return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-slate-600">{sessions.length} session{sessions.length === 1 ? "" : "s"} shown</p><button onClick={() => setShowCreate((value) => !value)} className="rounded-xl bg-[#071327] px-5 py-3 text-sm font-semibold text-white">{showCreate ? "Close" : "Create Session"}</button></div>{message ? <p className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950">{message}</p> : null}
    {showCreate ? <form onSubmit={create} className="grid gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:grid-cols-2"><h2 className="text-lg font-semibold text-[#071327] md:col-span-2">New class session</h2><label className="text-sm font-medium md:col-span-2">Cohort course<select name="cohort_course_id" required value={selectedOffering} onChange={(event) => setSelectedOffering(event.target.value)} className="mt-1 block w-full rounded-xl border border-slate-300 px-3 py-2"><option value="" disabled>Select an approved cohort course</option>{options.offerings.map((raw) => { const item = object(raw), cohort = relation(item.cohorts), course = relation(item.courses); return <option key={text(item.id)!} value={text(item.id)!}>{text(cohort.code)} · {text(course.code)} · {text(course.title)}</option>; })}</select></label>{suggestion ? <div className="rounded-xl bg-slate-50 p-4 text-sm leading-6 text-slate-600 md:col-span-2">Suggested from the offering: <strong>{humanize(suggestion.delivery_mode)}</strong> · {suggestion.schedule_text || "No schedule text set"}. Confirm all fields before saving.</div> : null}<TextInput name="title" label="Session title" required /><TextInput name="session_number" label="Session number" type="number" min="1" /><SelectInput name="session_type" label="Session type" values={sessionTypes} /><SelectInput name="delivery_mode" label="Delivery mode" values={sessionDeliveryModes} defaultValue={suggestion?.delivery_mode || "online"} /><TextInput name="scheduled_start_at" label="Scheduled start" type="datetime-local" /><TextInput name="scheduled_end_at" label="Scheduled end" type="datetime-local" /><TextInput name="timezone" label="Timezone" defaultValue="Africa/Lagos" /><label className="text-sm font-medium">Facilitator<select name="facilitator_id" defaultValue="" className="mt-1 block w-full rounded-xl border border-slate-300 px-3 py-2"><option value="">Use course assignment / not directly assigned</option>{options.facilitators.map((item) => <option key={item.id} value={item.id}>{item.display_name}</option>)}</select></label><TextInput name="live_join_url" label="Live class link" type="url" /><TextInput name="physical_location" label="Physical location" /><SelectInput name="session_status" label="Status" values={sessionStatuses} /><SelectInput name="visibility_status" label="Visibility" values={sessionVisibilityStatuses} defaultValue="enrolled_only" /><label className="text-sm font-medium md:col-span-2">Description<textarea name="description" rows={3} className="mt-1 block w-full rounded-xl border border-slate-300 p-3" /></label><label className="flex items-center gap-3 text-sm md:col-span-2"><input name="is_required" type="checkbox" defaultChecked /> Required session</label><button disabled={busy} className="rounded-xl bg-[#071327] px-5 py-3 text-sm font-semibold text-white disabled:opacity-50 md:col-span-2">{busy ? "Creating…" : "Create class session"}</button></form> : null}
    <form className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-3 xl:grid-cols-5"><input name="search" defaultValue={filters.search} placeholder="Title, course code or course" className="rounded-xl border border-slate-300 px-3 py-2 text-sm xl:col-span-2" /><select name="cohort" defaultValue={filters.cohort || ""} className="rounded-xl border border-slate-300 px-3 py-2 text-sm"><option value="">All cohorts</option>{cohortOptions.map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select><select name="course" defaultValue={filters.course || ""} className="rounded-xl border border-slate-300 px-3 py-2 text-sm"><option value="">All courses</option>{courseOptions.map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select><select name="category" defaultValue={filters.category || ""} className="rounded-xl border border-slate-300 px-3 py-2 text-sm"><option value="">All categories</option>{courseCategories.map((item) => <option key={item} value={item}>{humanize(item)}</option>)}</select><select name="route" defaultValue={filters.route || ""} className="rounded-xl border border-slate-300 px-3 py-2 text-sm"><option value="">All routes</option><option value="foundational">Foundational</option><option value="advanced">Advanced</option></select><select name="pathway" defaultValue={filters.pathway || ""} className="rounded-xl border border-slate-300 px-3 py-2 text-sm"><option value="">All pathways</option><option value="web_development">Web Development</option><option value="cybersecurity_foundations">Cybersecurity Foundations</option></select><select name="facilitator" defaultValue={filters.facilitator || ""} className="rounded-xl border border-slate-300 px-3 py-2 text-sm"><option value="">All facilitators</option>{options.facilitators.map((item) => <option key={item.id} value={item.id}>{item.display_name}</option>)}</select><select name="deliveryMode" defaultValue={filters.deliveryMode || ""} className="rounded-xl border border-slate-300 px-3 py-2 text-sm"><option value="">All delivery modes</option>{sessionDeliveryModes.map((item) => <option key={item} value={item}>{humanize(item)}</option>)}</select><select name="status" defaultValue={filters.status || ""} className="rounded-xl border border-slate-300 px-3 py-2 text-sm"><option value="">All statuses</option>{sessionStatuses.map((item) => <option key={item} value={item}>{humanize(item)}</option>)}</select><TextInput name="from" label="From" type="date" defaultValue={filters.from} compact /><TextInput name="to" label="To" type="date" defaultValue={filters.to} compact /><div className="flex gap-2"><button className="rounded-xl bg-[#071327] px-4 py-2 text-sm font-semibold text-white">Apply</button><Link href="/admin/sessions" className="rounded-xl border border-slate-300 px-4 py-2 text-sm font-semibold">Clear</Link></div></form>
    {sessions.length === 0 ? <EmptyState title="No class sessions found" detail="Create the first session manually or adjust the filters. Recurring schedule text is not converted into dated sessions automatically." /> : <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{sessionTableColumns.map((column) => <th key={column.key} className="px-4 py-3">{column.label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{sessions.map((raw) => { const row = object(raw), offering = relation(row.cohort_courses), course = relation(offering.courses), cohort = relation(offering.cohorts), facilitator = relation(row.facilitators), summary = summaryRelation(row.class_summaries), recordings = Array.isArray(row.class_recordings) ? row.class_recordings : [], past = typeof row.scheduled_start_at === "string" && Date.parse(row.scheduled_start_at) < Date.now(); const recordingStatus = recordings.length === 0 ? "No Recording" : recordings.some((item) => object(item).recording_status === "available") ? "available" : text(object(recordings[0]).recording_status); return <tr key={text(row.id)!} className={past ? "bg-slate-50/70 text-slate-600" : ""}><td className="px-4 py-4">{formatDate(text(row.scheduled_start_at), true)}{past ? <span className="mt-1 block text-xs font-semibold uppercase text-slate-400">Past</span> : null}</td><td className="px-4 py-4"><Link href={`/admin/sessions/${text(row.id)}`} className="font-semibold text-amber-800 hover:underline">{text(row.title)}</Link><span className="block text-xs text-slate-500">Session {row.session_number ?? "—"}</span></td><td className="px-4 py-4"><strong>{text(course.code)}</strong><span className="block max-w-56">{text(course.title)}</span></td><td className="px-4 py-4">{text(cohort.code)}</td><td className="px-4 py-4">{text(facilitator.display_name) || "Course assignment"}</td><td className="px-4 py-4"><StatusBadge value={text(row.delivery_mode)} /></td><td className="px-4 py-4"><StatusBadge value={text(row.session_status)} /></td><td className="px-4 py-4"><StatusBadge value={text(summary.summary_status) || "No Summary"} /></td><td className="px-4 py-4"><StatusBadge value={recordingStatus} /></td></tr>; })}</tbody></table></div>}
  </div>;
}
function TextInput({ name, label, type = "text", required, min, defaultValue, compact }: { name: string; label: string; type?: string; required?: boolean; min?: string; defaultValue?: string; compact?: boolean }) { return <label className={compact ? "text-xs font-semibold uppercase text-slate-500" : "text-sm font-medium"}>{label}<input name={name} type={type} required={required} min={min} defaultValue={defaultValue} className="mt-1 block w-full rounded-xl border border-slate-300 px-3 py-2 text-sm font-normal text-slate-900" /></label>; }
function SelectInput({ name, label, values, defaultValue }: { name: string; label: string; values: readonly string[]; defaultValue?: string }) { return <label className="text-sm font-medium">{label}<select name={name} defaultValue={defaultValue || values[0]} className="mt-1 block w-full rounded-xl border border-slate-300 px-3 py-2">{values.map((item) => <option key={item} value={item}>{humanize(item)}</option>)}</select></label>; }
function object(value: unknown) { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, string | number | boolean | null | undefined> : {}; }
function relation(value: unknown) { return Array.isArray(value) ? object(value[0]) : object(value); }
function summaryRelation(value: unknown) { return relation(value); }
function text(value: unknown) { return typeof value === "string" ? value : null; }
