"use client";

import { useState } from "react";

type Recording = { id: string; title: string; provider?: unknown };
type Evidence = Record<string, unknown>;

export function ZoomEvidenceImportPanel({ recordings, evidence, migrationRequired }: { recordings: Recording[]; evidence: Evidence[]; migrationRequired: boolean }) {
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const zoomRecordings = recordings.filter((item) => item.provider === "zoom");
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setMessage("");
    const response = await fetch("/api/admin/recordings/zoom-evidence/import", { method: "POST", body: new FormData(event.currentTarget) }); const data = await response.json(); setBusy(false);
    if (!response.ok) return setMessage(data.message || "Zoom viewing evidence could not be imported.");
    setMessage(`${data.imported} imported · ${data.matched} matched by registered email · ${data.unmatched} unmatched · ${data.duplicates} duplicates ignored.`); window.location.reload();
  }
  async function reconcile(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const recordingId = new FormData(event.currentTarget).get("recording_id"); const response = await fetch("/api/admin/recordings/zoom-evidence/reconcile", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ recording_id: recordingId }) }); const data = await response.json(); setBusy(false); if (!response.ok) return setMessage(data.message || "Zoom viewing evidence could not be reconciled."); setMessage(`${data.matched} previously unmatched records reconciled by registered email · ${data.remaining} remain unmatched.`); window.location.reload(); }
  return <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-semibold">Zoom viewing evidence</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Require viewer registration on official Zoom cloud recordings and instruct students to use their REALMS registered email. Import Zoom viewer-registration or analytics CSV data here. Matching uses that email—not display name. Zoom reported view duration is retained as provider evidence and is never labelled unique watch duration.</p></div><span className="rounded-full border border-slate-300 px-3 py-1 text-xs font-semibold">Zoom Cloud Recording · Verification: Zoom evidence + REALMS learning checks</span></div>
    {migrationRequired ? <p className="mt-4 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950">Apply the reviewed Zoom viewing-evidence migration before importing evidence.</p> : null}
    {message ? <p role="status" className="mt-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-950">{message}</p> : null}
    <form onSubmit={submit} className="mt-5 grid gap-3 md:grid-cols-3"><label className="text-sm font-medium">Zoom recording<select name="recording_id" required className="mt-1 block min-h-11 w-full rounded-lg border border-slate-300 px-3"><option value="">Choose recording</option>{zoomRecordings.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label className="text-sm font-medium md:col-span-2">Zoom viewer evidence CSV<input name="evidence_csv" type="file" accept=".csv,text/csv" required className="mt-1 block min-h-11 w-full rounded-lg border border-slate-300 p-2" /></label><button disabled={busy || migrationRequired || !zoomRecordings.length} className="rounded-lg bg-[#0b315c] px-4 py-2 font-semibold text-white disabled:opacity-50 md:col-span-3">{busy ? "Importing…" : "Import and reconcile by registered email"}</button></form>
    <form onSubmit={reconcile} className="mt-4 flex flex-wrap gap-3"><select name="recording_id" required className="min-h-11 rounded-lg border border-slate-300 px-3"><option value="">Choose Zoom recording to reconcile</option>{zoomRecordings.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><button disabled={busy || migrationRequired} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold disabled:opacity-50">Reconcile unmatched evidence</button></form>
    <h3 className="mt-7 font-semibold">Unmatched viewer queue</h3>{evidence.filter((item) => item.evidence_status === "unmatched").length ? <div className="mt-3 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead><tr>{["Viewer", "Email", "Recording identifier", "Viewed", "Zoom reported view duration"].map((label) => <th key={label} className="border-b px-3 py-2">{label}</th>)}</tr></thead><tbody>{evidence.filter((item) => item.evidence_status === "unmatched").map((item) => <tr key={String(item.id)}><td className="border-b px-3 py-2">{String(item.viewer_name || "Not supplied")}</td><td className="border-b px-3 py-2">{String(item.viewer_email)}</td><td className="border-b px-3 py-2">{String(item.zoom_recording_identifier)}</td><td className="border-b px-3 py-2">{item.viewed_at ? new Date(String(item.viewed_at)).toLocaleString("en-NG") : "Not supplied"}</td><td className="border-b px-3 py-2">{item.zoom_reported_view_duration_seconds == null ? "Not supplied" : `${Number(item.zoom_reported_view_duration_seconds)} seconds`}</td></tr>)}</tbody></table></div> : <p className="mt-3 text-sm text-slate-600">No unmatched Zoom viewer evidence.</p>}
  </section>;
}

export function ZoomEvidenceReview({ assignmentId, evidence, migrationRequired }: { assignmentId: string; evidence: Evidence[]; migrationRequired: boolean }) {
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [note, setNote] = useState("");
  async function review(evidenceId: string, decision: "verify" | "reject") { if (!note.trim()) return setMessage("Enter a review note before deciding Zoom evidence."); setBusy(true); const response = await fetch(`/api/admin/recordings/${assignmentId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "review_zoom_evidence", evidence_id: evidenceId, decision, note }) }); const data = await response.json(); setBusy(false); if (!response.ok) return setMessage(data.message || "Zoom evidence review failed."); window.location.reload(); }
  if (migrationRequired) return <p className="text-sm text-amber-900">Zoom evidence storage migration is not applied.</p>;
  if (!evidence.length) return <p className="text-sm text-slate-600">No Zoom viewer evidence is matched to this assignment.</p>;
  return <div className="space-y-4">{message ? <p role="status" className="rounded-xl bg-amber-50 p-3 text-sm text-amber-950">{message}</p> : null}<label className="block text-sm font-medium">Review note<textarea value={note} onChange={(event) => setNote(event.target.value)} rows={3} className="mt-1 block w-full rounded-lg border border-slate-300 p-3" /></label>{evidence.map((item) => <article key={String(item.id)} className="rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap justify-between gap-3"><div><strong>{String(item.viewer_name || item.viewer_email)}</strong><p className="text-sm text-slate-600">Matched by registered email: {String(item.viewer_email)}</p></div><span className="text-xs font-semibold uppercase">{String(item.evidence_status)}</span></div><p className="mt-3 text-sm text-slate-600">Zoom reported view duration: {item.zoom_reported_view_duration_seconds == null ? "Not supplied" : `${Number(item.zoom_reported_view_duration_seconds)} seconds`} · {item.viewed_at ? new Date(String(item.viewed_at)).toLocaleString("en-NG") : "View time not supplied"}</p>{item.evidence_status === "matched" ? <div className="mt-3 flex gap-3"><button disabled={busy} onClick={() => void review(String(item.id), "verify")} className="rounded-lg bg-emerald-700 px-3 py-2 text-sm font-semibold text-white">Verify Zoom evidence</button><button disabled={busy} onClick={() => void review(String(item.id), "reject")} className="rounded-lg border border-rose-300 px-3 py-2 text-sm font-semibold text-rose-800">Reject</button></div> : null}</article>)}</div>;
}
