/* Server-rendered deadline groups intentionally use the request-time clock. */
/* eslint-disable react-hooks/purity */
import Link from "next/link";
import { StudentPanel, formatStudentDate } from "@/components/student/StudentUi";
import { requireRole } from "@/lib/lms/auth";
import { assessmentStudentStatus, courseLabel, fetchStudentAssignments } from "@/lib/lms/assessmentData";
import { humanizeAssessment } from "@/lib/lms/assessment";
import { requireLmsAdminClient } from "@/lib/lms/adminData";
type Row = Record<string, unknown>;
export default async function StudentAssignmentsPage() { const { user } = await requireRole("student"); const assignments = await fetchStudentAssignments(requireLmsAdminClient(), user.id); const groups: Array<[string, (item: Row) => boolean]> = [["Due Soon", (item) => assessmentStudentStatus(item) === "open" && Boolean(item.due_at && Date.parse(String(item.due_at)) <= Date.now() + 7 * 86400000)], ["Open Assignments", (item) => assessmentStudentStatus(item) === "open"], ["Submitted", (item) => Boolean(item.latest_submission) && assessmentStudentStatus(item) === "awaiting_review"], ["Awaiting Review", (item) => assessmentStudentStatus(item) === "awaiting_review"], ["Graded", (item) => assessmentStudentStatus(item) === "graded"], ["Late / Overdue", (item) => assessmentStudentStatus(item) === "overdue" || Boolean((item.latest_submission as Row | null)?.is_late)], ["Resubmission Required", (item) => assessmentStudentStatus(item) === "revision_required"]]; return <div className="space-y-6"><header><p className="text-sm font-semibold uppercase tracking-wider text-amber-700">Assessment</p><h1 className="mt-2 text-3xl font-semibold text-[#071327]">Assignments</h1><p className="mt-2 text-slate-600">Assignments, practicals, reflections, projects, reports, and capstones from your enrolled courses.</p></header>{groups.map(([title, predicate]) => { const items = (assignments as unknown as Row[]).filter(predicate); if (!items.length) return null; return <StudentPanel key={title} title={title}><div className="grid gap-3 lg:grid-cols-2">{items.map((item) => <Link key={String(item.id)} href={`/student/assignments/${String(item.id)}`} className="rounded-xl border border-slate-200 p-4 hover:border-amber-300"><p className="text-xs font-semibold uppercase text-amber-700">{courseLabel(item)}</p><h2 className="mt-2 font-semibold text-[#071327]">{String(item.title)}</h2><dl className="mt-3 grid grid-cols-2 gap-2 text-sm text-slate-600"><div><dt className="font-semibold text-slate-800">Type</dt><dd>{humanizeAssessment(String(item.assignment_type))}</dd></div><div><dt className="font-semibold text-slate-800">Due</dt><dd>{item.due_at ? formatStudentDate(String(item.due_at), true) : "No deadline"}</dd></div><div><dt className="font-semibold text-slate-800">Status</dt><dd>{humanizeAssessment(assessmentStudentStatus(item))}</dd></div></dl></Link>)}</div></StudentPanel>; })}{assignments.length === 0 ? <StudentPanel title="No published assignments"><p className="text-sm text-slate-600">There are no published assignments for your enrolled courses.</p></StudentPanel> : null}</div>; }
