"use client";

import { useRouter } from "next/navigation";
import { type FormEvent, useState } from "react";

const field = "min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm";

export function AnnouncementReadButton({ announcementId, read }: { announcementId: string; read: boolean }) { const router = useRouter(); const [busy, setBusy] = useState(false); if (read) return <span className="text-xs font-semibold text-emerald-700">Read</span>; return <button disabled={busy} onClick={async () => { setBusy(true); await fetch(`/api/alumni/announcements/${announcementId}/read`, { method: "POST" }); router.refresh(); setBusy(false); }} className="text-xs font-semibold text-amber-800">{busy ? "Saving…" : "Mark as read"}</button>; }

export function CertificateDownloadButton({ awardId }: { awardId: string }) { const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); return <div><button disabled={busy} onClick={async () => { setBusy(true); setMessage(""); const response = await fetch(`/api/alumni/certificates/${awardId}/download`, { method: "POST" }); const data = await response.json().catch(() => ({})); if (response.ok && data.url) window.location.assign(data.url); else setMessage(data.message || "A secure download could not be prepared."); setBusy(false); }} className="min-h-11 rounded-xl bg-[#071327] px-4 py-2 text-sm font-semibold text-white">{busy ? "Preparing…" : "Download Certificate"}</button>{message ? <p className="mt-2 text-sm text-rose-700">{message}</p> : null}</div>; }

export function ArchiveResourceButton({ resourceId, label }: { resourceId: string; label: string }) { const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); return <div><button disabled={busy} onClick={async () => { setBusy(true); setMessage(""); const response = await fetch(`/api/alumni/resources/${resourceId}/open`, { method: "POST" }); const data = await response.json().catch(() => ({})); if (response.ok && data.url) window.location.assign(data.url); else setMessage(data.message || "This resource could not be opened."); setBusy(false); }} className="font-semibold text-amber-800">{busy ? "Preparing…" : label}</button>{message ? <p className="text-xs text-rose-700">{message}</p> : null}</div>; }

export function OutcomeUpdateForm() { const router = useRouter(); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const payload: Record<string, unknown> = {}; for (const [key, value] of new FormData(event.currentTarget)) payload[key] = value; const response = await fetch("/api/alumni/outcomes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json().catch(() => ({})); setMessage(response.ok ? "Your voluntary outcome update was saved for private institutional review." : data.message || "The update could not be saved."); if (response.ok) { event.currentTarget.reset(); router.refresh(); } setBusy(false); }
  return <form onSubmit={submit} className="space-y-3 rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-xl font-semibold">Share a voluntary outcome update</h2><select name="outcome_type" required className={field}>{["employment", "business_project", "ministry_service", "mission_activity", "further_study", "community_impact", "practical_skill_application"].map((value) => <option key={value}>{value}</option>)}</select><div className="grid gap-3 sm:grid-cols-2"><input name="role_or_activity" placeholder="Role or activity" className={field} /><input name="organisation_or_ministry" placeholder="Organisation or ministry" className={field} /><input name="location_summary" placeholder="General location (no exact address)" className={field} /><input name="update_date" type="date" required className={field} /></div><textarea name="outcome_summary" required minLength={20} placeholder="Brief outcome summary" className={field} /><label className="block text-sm"><input name="may_contact_for_followup" type="checkbox" /> REALMS may contact me privately about this update.</label><label className="block rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm"><input name="testimony_use_consent" type="checkbox" /> I separately permit REALMS to contact me about possible testimony use. Submission alone never authorises publication.</label>{message ? <p role="status" className="text-sm text-amber-800">{message}</p> : null}<button disabled={busy} className="min-h-11 rounded-xl bg-[#071327] px-4 py-2 font-semibold text-white">{busy ? "Saving…" : "Submit Outcome Update"}</button></form>; }
