import Link from "next/link";

import { ArchiveResourceButton } from "@/components/alumni/AlumniActions";
import { AlumniPageHeader } from "@/components/alumni/AlumniShell";
import { fetchOwnAlumniArchive, resolveOwnAlumni } from "@/lib/lms/alumniData";
import { requireRole } from "@/lib/lms/auth";
import { humanizeResult } from "@/lib/lms/results";
import { createSupabaseServerClient } from "@/lib/supabase/server";

type Row = Record<string, unknown>;
function relation(value: unknown): Row { if (Array.isArray(value)) return (value[0] ?? {}) as Row; return value && typeof value === "object" ? value as Row : {}; }
function list(value: unknown) { if (!Array.isArray(value) || !value.length) return <p className="text-sm text-slate-500">Not recorded.</p>; return <ul className="list-disc space-y-1 pl-5 text-sm leading-6 text-slate-700">{value.map((item, index) => <li key={index}>{typeof item === "string" ? item : String((item as Row).text ?? (item as Row).title ?? "Structured item")}</li>)}</ul>; }

export default async function AlumniLearningArchivePage() {
  const { user } = await requireRole("alumni"); const supabase = await createSupabaseServerClient(); const alumni = await resolveOwnAlumni(supabase, user.id); const data = await fetchOwnAlumniArchive(supabase, String(alumni.id));
  const sessionsByOffering = new Map<string, Row[]>(); for (const session of data.sessions) sessionsByOffering.set(session.cohort_course_id, [...(sessionsByOffering.get(session.cohort_course_id) ?? []), session]);
  return <><AlumniPageHeader eyebrow="Permanent Learning Record" title="Learning Archive" description="Published class-summary snapshots for your completed route and skill pathway. Historical superseded versions remain preserved internally."/><div className="space-y-7">{data.courses.map((course) => {
    const programme = relation(course.alumni_programme_records); const summaries = course.alumni_summary_archive_items as Row[]; const sessions = sessionsByOffering.get(course.cohort_course_id) ?? [];
    return <section key={course.id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><header className="bg-[#071327] p-5 text-white"><p className="text-xs font-semibold uppercase tracking-wide text-[var(--realm-gold-soft)]">{humanizeResult(course.category_snapshot)} · {String(programme.cohort_name_snapshot)}</p><h2 className="mt-2 text-2xl font-semibold">{String(course.course_code_snapshot)} · {String(course.course_title_snapshot)}</h2></header><div className="space-y-5 p-5">{summaries.map((summary) => {
      const snapshot = relation(summary.summary_snapshot);
      return <article key={String(summary.id)} className="rounded-xl border border-slate-200 p-5"><p className="text-xs font-semibold uppercase tracking-wide text-amber-800">{summary.session_date_snapshot ? new Date(String(summary.session_date_snapshot)).toLocaleDateString("en-NG") : "Session date unavailable"} · Version {String(summary.source_version_number)}</p><h3 className="mt-2 text-xl font-semibold">{String(summary.summary_title_snapshot || summary.session_title_snapshot)}</h3><div className="mt-5 grid gap-5 lg:grid-cols-2">{[["Learning Objectives", snapshot.learning_objectives], ["Key Teaching Points", snapshot.key_teaching_points], ["Scripture / References", snapshot.scripture_references], ["Important Concepts", snapshot.important_concepts], ["Practical Applications", snapshot.practical_applications], ["Action Points", snapshot.action_points], ["Recommended Resources", snapshot.recommended_resources]].map(([label, value]) => <section key={String(label)}><h4 className="mb-2 font-semibold">{String(label)}</h4>{list(value)}</section>)}<section><h4 className="mb-2 font-semibold">Additional Notes</h4><p className="whitespace-pre-line text-sm leading-6 text-slate-700">{String(snapshot.additional_notes ?? "Not recorded.")}</p></section></div></article>;
    })}{sessions.map((session) => { const resources = session.session_resources as Row[]; if (!resources.length) return null; return <article key={String(session.id)} className="rounded-xl bg-slate-50 p-4"><h3 className="font-semibold">Archive Resources · {String(session.title)}</h3><ul className="mt-3 space-y-2">{resources.map((resource) => <li key={String(resource.id)}><ArchiveResourceButton resourceId={String(resource.id)} label={String(resource.title)} /></li>)}</ul></article>; })}{!summaries.length ? <p className="text-sm text-slate-600">No published summary snapshot is available for this course.</p> : null}</div></section>;
  })}{data.recordings.length ? <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-semibold">Time-Limited Recording Access</h2><p className="mt-2 text-sm text-slate-600">Recording access is a controlled grant, not a permanent programme requirement.</p><ul className="mt-4 space-y-3">{data.recordings.map((grant) => { const recording = relation(grant.class_recordings); return <li key={String(grant.id)} className="rounded-xl border border-slate-200 p-4"><p className="font-semibold">{String(recording.title)}</p>{recording.external_url ? <Link href={String(recording.external_url)} className="mt-2 inline-flex text-sm font-semibold text-amber-800">Open authorised recording</Link> : null}<p className="mt-2 text-xs text-slate-500">Access ends: {grant.available_until ? new Date(String(grant.available_until)).toLocaleString("en-NG") : "No earlier grant expiry recorded"}</p></li>; })}</ul></section> : null}</div></>;
}
