import Link from "next/link";

import { PortalShell } from "@/components/portal/PortalShell";
import { humanizeEngagement } from "@/lib/lms/engagement";
import { resolveFacilitatorAssessmentContext } from "@/lib/lms/facilitatorAssessments";
import { fetchFacilitatorEngagementIndicators } from "@/lib/lms/facilitatorEngagement";

export const dynamic = "force-dynamic";
function relation(value: unknown) { return Array.isArray(value) ? (value[0] ?? {}) : (value ?? {}) as Record<string, unknown>; }
export default async function FacilitatorEngagementPage() { const context = await resolveFacilitatorAssessmentContext(); const rows = await fetchFacilitatorEngagementIndicators(context.supabase, context.offeringIds); return <PortalShell eyebrow="Faculty Portal" title="Assigned-Course Engagement" description="Limited academic indicators for your assigned courses only. Welfare records, student responses, referrals, private evidence, and review notes are excluded."><Link href="/facilitator" className="font-semibold text-[var(--realm-gold-soft)]">← Faculty home</Link><div className="mt-6 grid gap-4">{rows.map((item) => { const course = relation(item.offering.courses) as Record<string, unknown>; const cohort = relation(item.offering.cohorts) as Record<string, unknown>; return <article key={item.courseEnrollmentId} className="rounded-2xl border border-white/10 bg-white/[0.055] p-5"><p className="text-xs uppercase tracking-wide text-[var(--realm-gold-soft)]">{String(course.code)} · {String(cohort.code)}</p><h2 className="mt-2 text-xl font-semibold">{String(item.student.preferred_name || item.student.legal_name)} · {String(item.student.student_number)}</h2><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-3 lg:grid-cols-6">{Object.entries(item).filter(([key]) => !["courseEnrollmentId", "student", "offering"].includes(key)).map(([key, value]) => <div key={key}><dt className="text-white/55">{humanizeEngagement(key.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`))}</dt><dd className="mt-1 font-semibold">{String(value)}</dd></div>)}</dl></article>; })}{!rows.length ? <p className="rounded-2xl border border-white/10 bg-white/[0.055] p-8 text-white/65">No current academic engagement indicator is visible in your assigned courses.</p> : null}</div></PortalShell>; }
