import type { Metadata } from "next";

import { DataCard, EmptyState, formatStudentDate, humanizeStudentValue, StudentPanel } from "@/components/student/StudentUi";
import { attendanceStatusLabels, deliveryRouteLabels } from "@/lib/lms/attendance";
import { humanizeAbsenceValue } from "@/lib/lms/absence";
import { requireRole } from "@/lib/lms/auth";
import { getStudentAttendanceData } from "@/lib/lms/studentAttendance";

export const metadata: Metadata = { title: "My Attendance | REALMS Institute" };

export default async function StudentAttendancePage() {
  const { user } = await requireRole("student"); const data = await getStudentAttendanceData(user.id);
  return <div className="space-y-6"><header className="rounded-3xl bg-[linear-gradient(135deg,#092648,#0e3a68)] p-6 text-white shadow-lg md:p-8"><p className="text-sm font-semibold text-[var(--realm-gold-soft)]">Student Attendance</p><h1 className="mt-2 text-3xl font-semibold tracking-tight md:text-4xl">My Attendance</h1><p className="mt-3 max-w-3xl leading-7 text-white/75">Attendance records are reviewed from class evidence and finalized by authorized REALMS staff.</p></header>
    {data.reviewRequired ? <div role="status" className="rounded-2xl border border-amber-300 bg-amber-50 p-5 text-amber-950"><h2 className="font-semibold">Attendance Review Required</h2><p className="mt-1 text-sm leading-6">Your finalized absence units are above the programme review threshold. This does not automatically withdraw, suspend, or defer your enrolment.</p></div> : null}
    <StudentPanel title="Attendance Summary" description={data.finalizedCount ? "Calculated from finalized attendance records only." : "Attendance records will appear after your required class sessions begin."}><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><DataCard label="Finalized Sessions" value={String(data.finalizedCount)} /><DataCard label="Attendance Units Used" value={`${data.totalAbsenceUnits} of ${data.maximumAbsenceUnits}`} /><DataCard label="Remaining Permitted Units" value={String(data.remainingAbsenceUnits)} /><DataCard label="Attendance Review" value={data.reviewRequired ? "Required" : "Not Required"} /></div></StudentPanel>
    <StudentPanel title="Status Counts"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(data.counts).map(([status, count]) => <DataCard key={status} label={attendanceStatusLabels[status as keyof typeof attendanceStatusLabels]} value={String(count)} />)}</div></StudentPanel>
    <StudentPanel title="Attendance Policy"><div className="space-y-3 text-sm leading-6 text-slate-700"><p>REALMS records attendance for required sessions and activities. Approved absence does not automatically remove the learning requirement. Students may still be required to complete assigned catch-up work.</p><p>More than the permitted attendance limit triggers institutional review. Decisions are made after fair consideration and are not automatic.</p><p>Exceeding the published attendance limit triggers an attendance review and may affect programme continuation.</p></div></StudentPanel>
    <StudentPanel title="Attendance History" description="If you believe a finalized record is incorrect, contact REALMS Institute for a fair administrative review. Students cannot change attendance records directly.">{data.history.length ? <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-3 py-3">Date</th><th className="px-3 py-3">Course</th><th className="px-3 py-3">Session</th><th className="px-3 py-3">Delivery Route</th><th className="px-3 py-3">Attendance Status</th><th className="px-3 py-3">Absence / Make-Up</th></tr></thead><tbody className="divide-y divide-slate-200">{data.history.map((item) => <tr key={item.id}><td className="px-3 py-4">{formatStudentDate(item.date)}</td><td className="px-3 py-4"><p className="font-semibold text-[#071327]">{item.courseCode}</p><p className="text-xs text-slate-500">{item.courseTitle}</p></td><td className="px-3 py-4">{item.sessionTitle}</td><td className="px-3 py-4">{deliveryRouteLabels[item.route]}</td><td className="px-3 py-4">{humanizeStudentValue(attendanceStatusLabels[item.status])}</td><td className="px-3 py-4">{item.absenceRequestStatus ? <span className="block">Request: {humanizeAbsenceValue(item.absenceRequestStatus)}</span> : null}{item.makeupStatus ? <span className="block text-xs text-slate-500">Make-Up: {humanizeAbsenceValue(item.makeupStatus)}</span> : !item.absenceRequestStatus ? "—" : null}</td></tr>)}</tbody></table></div> : <EmptyState>No attendance records are available yet.</EmptyState>}</StudentPanel>
  </div>;
}
