import Link from "next/link";

import { AlumniPageHeader } from "@/components/alumni/AlumniShell";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { requireRole } from "@/lib/lms/auth";
import { fetchOwnAlumniDashboard } from "@/lib/lms/alumniData";
import { humanizeResult } from "@/lib/lms/results";

export default async function AlumniDashboardPage() { const { user } = await requireRole("alumni"); const data = await fetchOwnAlumniDashboard(await createSupabaseServerClient(), user.id); const latest = data.programmes[0]; const name = String(data.student.preferred_name || data.student.legal_name || "Alumnus"); return <><AlumniPageHeader eyebrow="REALMS Alumni" title={`Welcome, ${name}`} description="Your completed programmes, permanent learning archive, institutional awards and current alumni updates."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Alumni Number", data.alumni.alumni_number ?? "Pending"], ["Completed Programmes", data.programmes.length], ["Latest Cohort", latest?.cohort_name_snapshot ?? "Not available"], ["Archive Access", data.alumni.learning_archive_access ? "Active" : "Restricted"]].map(([label, value]) => <article key={String(label)} className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-xl font-semibold">{String(value)}</p></article>)}</div>{latest ? <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-semibold">Most Recent Completion</h2><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-3"><p><strong>Programme:</strong> {String(latest.programme_name)}</p><p><strong>Cohort:</strong> {String(latest.cohort_name_snapshot)}</p><p><strong>Route:</strong> {humanizeResult(String(latest.discipleship_route))}</p><p><strong>Pathway:</strong> {humanizeResult(String(latest.skill_pathway))}</p><p><strong>Completion:</strong> {String(latest.completion_date)}</p><p><strong>Graduation:</strong> {String(latest.graduation_date ?? "Not separately scheduled")}</p></dl></section> : null}<div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[["/alumni/learning-archive", "Learning Archive"], ["/alumni/results", "Published Results"], ["/alumni/certificates", "Certificates"], ["/alumni/announcements", "Announcements"], ["/alumni/profile", "Outcome Update"], ["/register?applicant_type=realms_alumnus", "Apply for Further REALMS Training"]].map(([href, label]) => <Link key={href} href={href} className="rounded-2xl bg-[#071327] p-5 font-semibold text-white">{label}</Link>)}</div></>; }
